TwitchDownloaderCore/TwitchHelper.cs

This should close #104, let me know if any issues.
Note that it uses `name` as the underlying id will be different, but it is the same thirdparty emote (e.g. christmas themed LULW etc.).

Correctly load embedded thirdparty emotes if available

---

TwitchDownloaderCLI/Options.cs
TwitchDownloaderCore/ChatRenderer.cs

It seems like on Mac, the default SKColorType is Rgba8888 instead of Bgra8888, so I was getting a color issue
Before:
After:

Add rgba support on mac

---

TwitchDownloaderCLI/Program.cs

The CLI application no longer throws an error requiring ffmpeg when you are just trying to download the chat.

Chat download doesn't require ffmpeg

---

TwitchDownloaderCore/ChatRenderer.cs
TwitchDownloaderCore/TwitchHelper.cs
TwitchDownloaderCore/TwitchObjects/TwitchEmote.cs

Add 7tv animated emote support for webp
Need to have special case for static webp when the frame count is 0.
Also made the cache folder use the correct file endings so it is easy to debug and see the animated files
Example files:
[7tv_chat_testing1.json.txt](https://github.com/lay295/TwitchDownloader/files/7214674/7tv_chat_testing1.json.txt)
[7tv_chat_testing2.json.txt](https://github.com/lay295/TwitchDownloader/files/7214675/7tv_chat_testing2.json.txt)

7tv animated emotes

---

TwitchDownloaderWPF/PageVodDownload.xaml
TwitchDownloaderWPF/PageVodDownload.xaml.cs

If vod crop start/end checkbox is not enabled - the hour, minute, second time boxes are disabled.
Disabled:
Enabled:

toggle disable on crop time boxes via checkbox 

---

TwitchDownloaderCLI/Program.cs

Previous conditional was always true
`(inputOptions.RunMode != RunMode.ChatDownload || inputOptions.RunMode != RunMode.ClipDownload)`
**Examples**
inputOptions.RunMode is RunMode.ChatDownload -> false || true = true
inputOptions.RunMode is RunMode.ClipDownload-> true || false = true
inputOptions.RunMode is RunMode.VideoDownload-> true || true = true

ffmpeg not required if RunMode is ChatDownload or ClipDownload

---

.github/workflows/build.yml
TwitchDownloaderCLI/Properties/PublishProfiles/Linux.pubxml
TwitchDownloaderCLI/Properties/PublishProfiles/LinuxAlpine.pubxml
TwitchDownloaderCLI/Properties/PublishProfiles/LinuxArm.pubxml
TwitchDownloaderCLI/Properties/PublishProfiles/MacOS.pubxml
TwitchDownloaderCLI/Properties/PublishProfiles/Windows.pubxml
TwitchDownloaderCLI/TwitchDownloaderCLI.csproj
TwitchDownloaderCore/Properties/PublishProfiles/FolderProfile.pubxml
TwitchDownloaderCore/TwitchDownloaderCore.csproj

Or could leave `netstandard2.0` for `Core`.
But who uses net framework today for new projects.
And CLI is available cross-platform anyways.

Moving the rest of projects to net6.0

---

TwitchDownloaderCLI/Options.cs
TwitchDownloaderCLI/Program.cs
TwitchDownloaderCLI/Properties/launchSettings.json
TwitchDownloaderCLI/README.md
TwitchDownloaderCore/ChatDownloader.cs
TwitchDownloaderCore/Options/ChatDownloadOptions.cs
TwitchDownloaderWPF/PageChatDownload.xaml
TwitchDownloaderWPF/PageChatDownload.xaml.cs

Fixes #202
Implements an asynchronous chat fetcher. Defaults to 10 parallel connections, limited it to 50 for rate limiting. The default and max can be changed.
A benchmark on the first hour of 1446466302:
Task no.|Speed|Time
-|-|-
1|~1.3 Mbps|3m31s
10|~12 Mbps|25s
50|~36 Mbps|10s
Final percentages can be slower due to rate limiting kicking in.

Parallel chat downloads

---

TwitchDownloaderCore/VideoDownloader.cs

This ensures that, for instance, -q "360p" also works when only "360p30" is available.
I don't know if Twitch introduced the "p30" options recently, but I believe it is easier for CLI users if they only have to provide "360p" instead of looking up whether the available quality is "360p" or "360p30". This also avoids the fallback to the highest quality. 
Example VODS:
https://www.twitch.tv/videos/1625525138
Provides only "___p30" options.
https://www.twitch.tv/videos/1631016426
Provides the regular "___p" options.

User provided video quality is no longer required to match the available video qualities exactly

---

LICENSE.txt
README.md
TwitchDownloaderCLI/README.md

- I tested 1.50.5 CLI on an Intel Macbook and it mostly worked, updated README to reflect that.
- Added a reference to an [AUR package](https://aur.archlinux.org/packages/twitch-downloader-gui) for twitch-downloader-gui from the same maintainer of the CLI [AUR package](https://aur.archlinux.org/packages/twitch-downloader-bin)
- Updated the copyright date, added word wrap, and added a header to the license

Readme and license updates

---

TwitchDownloaderCLI/Program.cs

Fixing code for extension which is not .json or .html to assume it is plain text as currently it only makes it plain text if no extension. It does not set output format if it has an extension but it is not json or html.

Fix #397 so any extension not .json or .html is txt

---

TwitchDownloaderCore/TwitchHelper.cs
TwitchDownloaderCore/TwitchObjects/stvEmoteFlags.cs

Migrate to 7TV v3 api

---

.github/ISSUE_TEMPLATE/bug_report.yaml

Makes troubleshooting CLI/GUI specific issues much easier since users usually don't mention which edition they're using

Add release edition to bug report template

---

.github/workflows/build.yml

- Rename GUI from "Release" to "TwitchDownloaderGUI-\<version\>-Windows-x64"
- Add version number to every release zip file name
Fixes #357

Add version number to release asset names

---

TwitchDownloaderCLI/Modes/Arguments/ChatRenderArgs.cs
TwitchDownloaderCore/TwitchHelper.cs

- Fixed emoji zip not obeying custom cache and persisting after use
- Fixed emojis not being fetched on Linux
- Fixed not checking for 7TV v3 API mentioning emotes without hosted files
- Fixed Inter Embedded not being utilized by default
Fixes #433 
Fixes #432

Misc Chat Render fixes

---

TwitchDownloaderCore/ChatDownloader.cs

- Fixed comments sent on videoStart being discarded
- Fixed comments with duplicate offsets being discarded
Fixes #438

Chatdownload patch

---

.github/workflows/build-pr.yml
.github/workflows/build.yml
TwitchDownloaderWPF/TwitchDownloader.csproj

- Removed debug files from build via publish arguments
- Remove theme folder from build process as they are extracted at runtime anyways
- Specify `dotnet restore TwitchDownloaderWPF` to reduce build job times[^1]
[^1]:Build logs report restoring CLI takes an additional ~45s

Remove debug files from GUI build

---

TwitchDownloaderCore/ChatDownloader.cs
TwitchDownloaderCore/ChatRenderer.cs
TwitchDownloaderCore/TwitchHelper.cs
TwitchDownloaderCore/TwitchObjects/ChatRoot.cs
TwitchDownloaderCore/TwitchObjects/ChatRootInfo.cs
TwitchDownloaderCore/TwitchObjects/Gql/GqlCheerResponse.cs
TwitchDownloaderCore/TwitchObjects/Gql/GqlClipResponse.cs
TwitchDownloaderCore/TwitchObjects/Gql/GqlClipSearchResponse.cs
TwitchDownloaderCore/TwitchObjects/Gql/GqlCommentResponse.cs
TwitchDownloaderCore/TwitchObjects/Gql/GqlVideoResponse.cs
TwitchDownloaderCore/TwitchObjects/Gql/GqlVideoSearchResponse.cs
TwitchDownloaderCore/TwitchObjects/GqlVideoResponse.cs
TwitchDownloaderWPF/PageChatDownload.xaml.cs
TwitchDownloaderWPF/PageClipDownload.xaml.cs
TwitchDownloaderWPF/PageVodDownload.xaml.cs
TwitchDownloaderWPF/WindowMassDownload.xaml.cs
TwitchDownloaderWPF/WindowUrlList.xaml.cs

- Move GQL classes to `TwitchObjects.Gql`
- Put `ChatRoot` class in namespace `TwitchObjects`
- Rename `ChatRoot.VideoTime` to `ChatRoot.Video`
- Add `title`, `id`, `created_at`, and `length` fields to `ChatRoot.Video`
- Add `ChatRootInfo` class
- Add `ChatRootVersion` class for keeping track of compatibility
I also created some unit tests to ensure sure the ChatRootVersion operators worked correctly. If you would like for these to be added this PR, I can do that. It could be nice to have some unit tests for several parts of Core

Add additional information to chat jsons

---

TwitchDownloaderCLI/Modes/Arguments/ChatRenderArgs.cs
TwitchDownloaderCLI/Modes/DownloadChat.cs
TwitchDownloaderCLI/Modes/DownloadClip.cs
TwitchDownloaderCLI/Modes/DownloadVideo.cs
TwitchDownloaderCLI/Modes/RenderChat.cs
TwitchDownloaderCLI/Modes/UpdateChat.cs
TwitchDownloaderCLI/Program.cs
TwitchDownloaderCLI/README.md
TwitchDownloaderCLI/Tools/PreParseArgs.cs
TwitchDownloaderCLI/Tools/ProgressHandler.cs
TwitchDownloaderCore/ChatRenderer.cs
TwitchDownloaderCore/Options/ChatRenderOptions.cs
TwitchDownloaderCore/Tools/DriveHelper.cs
TwitchDownloaderCore/Tools/FfmpegProcess.cs
TwitchDownloaderCore/VideoDownloader.cs
TwitchDownloaderWPF/App.xaml.cs
TwitchDownloaderWPF/PageChatDownload.xaml.cs
TwitchDownloaderWPF/PageChatRender.xaml
TwitchDownloaderWPF/PageChatRender.xaml.cs
TwitchDownloaderWPF/PageChatUpdate.xaml.cs
TwitchDownloaderWPF/PageClipDownload.xaml.cs
TwitchDownloaderWPF/PageVodDownload.xaml
TwitchDownloaderWPF/PageVodDownload.xaml.cs
TwitchDownloaderWPF/SettingsPage.xaml
TwitchDownloaderWPF/SettingsPage.xaml.cs

- Fix pipe end errors when rendering to a drive that disconnects during high loads[^1] (Fixes #465)
- Cleanup CLI runmodes
- Cleanup CLI ProgressHandler
- Cleanup progress report handling in GUI
[^1]: Because of the constant drive checks, I noticed a *very* slight performance dip when rendering from 201s -> 203s (41.2x -> 40.9x)

Unstable drive fix

---

TwitchDownloaderCore/Options/VideoDownloadOptions.cs
TwitchDownloaderCore/VideoDownloader.cs
TwitchDownloaderWPF/InfoHelper.cs
TwitchDownloaderWPF/MainWindow.xaml.cs
TwitchDownloaderWPF/PageChatDownload.xaml.cs
TwitchDownloaderWPF/PageChatUpdate.xaml.cs
TwitchDownloaderWPF/PageClipDownload.xaml.cs
TwitchDownloaderWPF/PageVodDownload.xaml.cs
TwitchDownloaderWPF/TwitchTasks/ChatDownloadTask.cs
TwitchDownloaderWPF/TwitchTasks/ChatRenderTask.cs
TwitchDownloaderWPF/TwitchTasks/ChatUpdateTask .cs
TwitchDownloaderWPF/TwitchTasks/ClipDownloadTask.cs
TwitchDownloaderWPF/TwitchTasks/ITwitchTask.cs
TwitchDownloaderWPF/TwitchTasks/VodDownloadTask.cs
TwitchDownloaderWPF/WindowQueueOptions.xaml.cs

- Extract some code into methods for easier management and cleaner stack traces[^1]
- Catch IOException when cleaning up
- Make some methods static
- Remove some redundant code
- Dispose of TwitchTask token sources once completed/canceled
- Add 404 thumbnail
- Move the autoupdate preprocessor so the import isn't imcorrectly marked as unnecessary; intellisense is stupid.
[^1]: Hopefully this let's us catch the cause of #401 so we can throw a custom exception message instead or wait and retry.

Minor refactoring

---

TwitchDownloaderWPF/PageChatRender.xaml.cs

- Move Nvenc H264 to use modern presets instead of deprecated ones
- Add Nvenc H265
- Increase the speed of VP9 encoding without affecting the quality by more than 5% (VMAF and SSIM measurements)
- Allow H264 and H265 in more containers as they are supported

Update chat render video codec presets

---

TwitchDownloaderCLI/Modes/Arguments/ChatDownloadArgs.cs
TwitchDownloaderCLI/Modes/Arguments/ClipDownloadArgs.cs
TwitchDownloaderCLI/Modes/Arguments/VideoDownloadArgs.cs
TwitchDownloaderCLI/Modes/DownloadChat.cs
TwitchDownloaderCLI/Modes/DownloadClip.cs
TwitchDownloaderCLI/Modes/DownloadVideo.cs
TwitchDownloaderCLI/README.md

Supersedes #506 in order to not break backwards compatibility and to support all 3 downloaders.
Technically co-authored by @Teknoist

Support URLs in video, clip, chat downloading in CLI

---

TwitchDownloaderWPF/App.xaml
TwitchDownloaderWPF/App.xaml.cs
TwitchDownloaderWPF/WindowQueueOptions.xaml.cs

Just reading about some better practices is all. I'll likely also switch to `IHttpClientFactory` in a later PR to fix the issues with using a static `HttpClient`.

Print unhandled gui exceptions before exiting

---

.github/ISSUE_TEMPLATE/bug_report.yaml

Some users have neglected the edition dropdown, so making GUI the default was not a great idea.

Add 'unsure' and default 'select an option' to bug report edition dropdown

---

TwitchDownloaderCore/ChatDownloader.cs

GQL doesn't return it and also combines all the cheers into a single Cheer### word making emulating old behaviour harder.
- Fixes #519 
I'm a bit torn on if and how we should go about emulating old behaviour in the render.
1. Splitting the total into highest bit quantities is an option.
2. So is just drawing the highest quantity cheermote + the total amount cheered to partially emulate Twitch.[^1]
We would want to do a date/chatrootversion check though to preserve old behaviour with chats from v5.
3. Or we could just do nothing and let it print the highest quantity cheermote as it does right now.
No matter what we choose users will probably complain :P
A bit total of 5100 was probably a Cheer5000 + Cheer100, but only a Cheer5000 is rendered because there is only one 'Cheer###' in the …

Populate Message.bits_spent in newly downloaded chats

---

TwitchDownloaderWPF/PageChatRender.xaml
TwitchDownloaderWPF/PageChatRender.xaml.cs
TwitchDownloaderWPF/WindowQueueOptions.xaml.cs

Since chat renders are often slower than downloading videos and chat, I wanted to add support for selecting and queuing multiple chat files to be rendered at once.
With this change on the Chat Render tab, the JSON File selector now supports multiple files being selected at once and when you hit Render Chat (or Partial Render or Enqueue Render), it will prompt you to add all those render jobs to the task queue.

Multiselect chat rendering

---

TwitchDownloaderCore/ChatRenderer.cs

And the best part? It heavily simplified the emoji handling logic.
1.51.1:
Fix:
Note: The remaining emojis not getting rendered are Unicode 14.0 or higher. `NeoSmart.Unicode` does not support above 13.0, so we need to jump ship eventually.

Fix every rendering issue for all emojis less than 14.0

---

TwitchDownloaderCore/TwitchHelper.cs
TwitchDownloaderCore/VideoDownloader.cs

- Check for failed ffmpeg when copying videos
- Do not clear the cache on failed ffmpeg
- Generate log file of ffmpeg output in the cache directory, this should help us get to the root of #541 
- Log when old video caches are deleted

Do not clear cache on failed video download finalizing

---

TwitchDownloaderCore/Tools/FfmpegMetadata.cs

Fix null or empty video title causing crash when serializing metadata

---

TwitchDownloaderCore/ChatDownloader.cs

- Fix integer overflow crash when downloading chats where users pretend to send high amount cheers - fixes #596 
- Optimize bit regex
- The theoretical maximum cheer amount is now 9,999,999 bits, or $99,999. Surely nobody would donate $100,000USD in bits, or at least not in one message.
- I hyper optimized the pattern itself. It looks a bit crazy now but I promise it works the same as before [(click for visualization)](https://regexper.com/#%28%3F%3A%5Cs%7C%5E%29%28%3F%3A4Head%7CAnon%7CBi%28%3F%3AbleThumb%7CtBoss%29%7Cbday%7CC%28%3F%3Ah%28%3F%3Aeer%7Carity%29%7Corgo%29%7Ccheerwal%7CD%28%3F%3AansGame%7CoodleCheer%29%7CEleGiggle%7CF%28%3F%3ArankerZ%7CailFish%29%7CGoal%7CH%28%3F%3AeyGuys%7ColidayCheer%29%7CK%28%3F%3Aappa%7Creygasm%29%7CM%28%3F%3ArDestructoid%7Cuxy%29%7CNotLikeThis%7CP%28%3F%3 …

Chatdownload bits_spent patch

---

TwitchDownloaderCore/TwitchDownloaderCore.csproj
TwitchDownloaderCore/TwitchHelper.cs
TwitchDownloaderCore/TwitchObjects/Api/FFZEmote.cs
TwitchDownloaderCore/TwitchObjects/ChatRoot.cs
TwitchDownloaderCore/TwitchObjects/Gql/GqlVideoChapterResponse.cs

Migrating everything to `System.Text.Json` so we don't need to double-attribute every property with a custom name. Unfortunately `Xabe.Ffmpeg` implicitly installs a really old version of Newtonsoft so we can't eliminate it entirely :P Maybe I'll send them a PR to switch as well.

Fully remove Newtonsoft from Core

---

README.md

Since we've credited Google for Noto, I feel Twemoji shouldn't be left out, especially since switching between different emoji vendors is in plans.

Credit Twemoji

---

TwitchDownloaderCore/Chat/ChatJson.cs
TwitchDownloaderCore/ChatRenderer.cs
TwitchDownloaderCore/ChatUpdater.cs
TwitchDownloaderCore/Tools/TimeSpanExtensions.cs
TwitchDownloaderCore/TwitchObjects/ChatRoot.cs
TwitchDownloaderWPF/PageChatDownload.xaml.cs
TwitchDownloaderWPF/PageVodDownload.xaml.cs

- Significantly improves deserialization of legacy chats from 8d521f7 or before
- Fixes #728 
- Less allocations when deserializing `2d21h11m9s` time codes

Legacy chat deserialization improvements

---

TwitchDownloaderCore/TwitchHelper.cs
TwitchDownloaderCore/TwitchObjects/Api/FFZEmote.cs

Just checked and the BetterTTV FFZ endpoint now properly supports passing the correct _animated_ value for animated emotes
- Closes #577

Add support for animated FFZ emotes

---

TwitchDownloaderCLI/README.md

This corrects a small typo with oauth

fix: typo in cli docs

---

TwitchDownloaderCLI/Modes/Arguments/ChatRenderArgs.cs
TwitchDownloaderCLI/Modes/RenderChat.cs
TwitchDownloaderCLI/README.md
TwitchDownloaderCore/ChatRenderer.cs
TwitchDownloaderCore/Options/ChatRenderOptions.cs
TwitchDownloaderWPF/App.config
TwitchDownloaderWPF/PageChatRender.xaml
TwitchDownloaderWPF/PageChatRender.xaml.cs
TwitchDownloaderWPF/Properties/Settings.Designer.cs
TwitchDownloaderWPF/Properties/Settings.settings
TwitchDownloaderWPF/README.md
TwitchDownloaderWPF/Translations/Strings.Designer.cs
TwitchDownloaderWPF/Translations/Strings.fr.resx
TwitchDownloaderWPF/Translations/Strings.pl.resx
TwitchDownloaderWPF/Translations/Strings.resx
TwitchDownloaderWPF/Translations/Strings.ru.resx
TwitchDownloaderWPF/Translations/Strings.tr.resx
TwitchDownloaderWPF/Translations/Strings.zh.resx

- Add the ability to enable alternating message backgrounds. Closes #673 
- Example image:
- Clarify some CLI README text
- More explicit communication of unlisted 7tv emotes in the GUI code

Alternating message background colors

---

TwitchDownloaderCLI/Modes/Arguments/ChatDownloadArgs.cs
TwitchDownloaderCLI/README.md
TwitchDownloaderCore/Chat/ChatText.cs
TwitchDownloaderCore/Chat/TimestampFormat.cs

Gonna keep it short since the change is minimal.
Add support to extract chat timestamps with milliseconds information (txt file only)
In some cases having the milliseconds information of the timestamp of each message could be interesting.
As such, I propose the addition of a UTCMilliseconds option to the `timestamp-format` flag.
**_HOW_**
* add the `UtcMilliseconds` value to the `TimestampFormat` Enum.
* Add a condition to support this new option to the `ChatText` class.

Add support to milliseconds information in timestamp

---

TwitchDownloaderCLI/Modes/DownloadVideo.cs
TwitchDownloaderCore/VideoDownloader.cs
TwitchDownloaderWPF/PageVodDownload.xaml.cs
TwitchDownloaderWPF/TwitchTasks/VodDownloadTask.cs

- Use a `ConcurrentQueue` instead of LINQ for managing video part downloads
- Fallback to non-throttled download when receiving an unexpected EOF
- Add video part verification, redownload if needed
- This also brings us closer to implementing #544 
- Add a range check to ffmpeg finalization percentage because apparently it can be out of range
- Fixes #716

Videodownload patch

---

TwitchDownloaderCLI/Modes/Arguments/ChatDownloadArgs.cs
TwitchDownloaderCLI/Modes/DownloadChat.cs
TwitchDownloaderCore/Chat/ChatText.cs
TwitchDownloaderCore/ChatDownloader.cs
TwitchDownloaderCore/Options/ChatDownloadOptions.cs

**_WHY_**
My use case includes running this cli to download twitch chats, in a constraint environment (e.g, Rapsberri Pi).
The tool is great, but for large streams (with a lot of messages) the memory footprint can be big. 
for instance for:
https://www.twitch.tv/videos/1857424785
The tool takes around 510 mbs of memory (see images).
I was looking at the code, and I found out some points in which we could optimize. 
For instance, emotes, and Badges information are not used for txt files.
And creating these instances takes a lot of memory.
With the proposed changes I was able to reduce the memory usage significantly, to around: 360mbs for that particular case.
I also added a quiet mode (-q) option to the CLI, since some users might not be interested in keeping track of the progress (for …

Improve memory performance for txt chat download

---

TwitchDownloaderWPF/Behaviors/TextBoxTripleClickBehavior.cs
TwitchDownloaderWPF/PageChatDownload.xaml
TwitchDownloaderWPF/PageChatRender.xaml
TwitchDownloaderWPF/PageChatUpdate.xaml
TwitchDownloaderWPF/PageClipDownload.xaml
TwitchDownloaderWPF/PageVodDownload.xaml
TwitchDownloaderWPF/WindowMassDownload.xaml
TwitchDownloaderWPF/WindowQueueOptions.xaml
TwitchDownloaderWPF/WindowRangeSelect.xaml
TwitchDownloaderWPF/WindowSettings.xaml
TwitchDownloaderWPF/WindowUrlList.xaml

I hate the way I had to implement this. TL;DR we have to define it within every page/window it is used since defining it in app.xaml breaks the default visual template.
- Fixes #762

Add the ability to triple click text boxes to select a whole line

---

TwitchDownloaderWPF/PageChatDownload.xaml
TwitchDownloaderWPF/PageChatDownload.xaml.cs
TwitchDownloaderWPF/PageClipDownload.xaml
TwitchDownloaderWPF/PageClipDownload.xaml.cs
TwitchDownloaderWPF/PageVodDownload.xaml
TwitchDownloaderWPF/PageVodDownload.xaml.cs
TwitchDownloaderWPF/WindowMassDownload.xaml
TwitchDownloaderWPF/WindowMassDownload.xaml.cs

Allow pressing the enter key to search for vods/clips/channels

---

TwitchDownloaderCore/Tools/VideoSizeEstimator.cs
TwitchDownloaderCore/VideoDownloader.cs
TwitchDownloaderWPF/MainWindow.xaml.cs
TwitchDownloaderWPF/PageVodDownload.xaml.cs

A user recently mentioned some things about low drive space possibly causing weirdness for them. This should help notify users before anything like that happens

Print a log message if there may not be enough space to download/finalize a VOD

---

TwitchDownloaderCLI/Modes/DownloadClip.cs
TwitchDownloaderCore/ClipDownloader.cs
TwitchDownloaderCore/Extensions/StreamExtensions.cs
TwitchDownloaderCore/Tools/ThrottledStream.cs

- Add progress reporting to clip downloader
- Fix downloading clips with metadata not overwriting
- Fix crash when not providing a specific path to FFmpeg in the CLI
- Add `Span<byte>`/`ReadOnlySpan<byte>` overloads for `Read()`/`Write()` to ThrottledStream

Clip download progress

---

TwitchDownloaderWPF/WindowUrlList.xaml

The default style must be preserved to allow for the textbox to grow vertically.
- Fixes #781

Remove triple click from URL mass downloader text box

---

TwitchDownloaderWPF/PageChatDownload.xaml
TwitchDownloaderWPF/PageChatRender.xaml
TwitchDownloaderWPF/PageChatUpdate.xaml
TwitchDownloaderWPF/PageClipDownload.xaml
TwitchDownloaderWPF/PageVodDownload.xaml
TwitchDownloaderWPF/WindowMassDownload.xaml
TwitchDownloaderWPF/WindowQueueOptions.xaml
TwitchDownloaderWPF/WindowRangeSelect.xaml
TwitchDownloaderWPF/WindowSettings.xaml
TwitchDownloaderWPF/WindowUrlList.xaml

First draft of trying to fix https://github.com/lay295/TwitchDownloader/issues/762 / https://github.com/lay295/TwitchDownloader/pull/783 / https://github.com/lay295/TwitchDownloader/pull/765 / https://github.com/lay295/TwitchDownloader/issues/781
The problem seems to be with the template, not the rest of the style. Not sure if I missed some nuance there.
I just wanted to call attention to what seems to be a strict improvement; I'll try to do another pass later, but this is where I stop for now.

Triple click template problem

---

TwitchDownloaderCLI/Modes/DownloadChat.cs
TwitchDownloaderCLI/Modes/DownloadClip.cs
TwitchDownloaderCLI/Modes/DownloadVideo.cs
TwitchDownloaderCore/Tools/TwitchRegex.cs
TwitchDownloaderWPF/PageChatDownload.xaml.cs
TwitchDownloaderWPF/PageClipDownload.xaml.cs
TwitchDownloaderWPF/PageVodDownload.xaml.cs

- Add support for `twitch.tv/streamer/video/id` url formatting
- Fixes #787 
- Increase maintainability of video/clip id regex matching

Account for alternate video highlight url format

---

TwitchDownloaderWPF/Services/NativeFunctions.cs
TwitchDownloaderWPF/Services/ThemeService.cs
TwitchDownloaderWPF/Services/WindowsThemeService.cs

I setup a new device for someone recently and it shipped with 20H2 installed. It's not unreasonable to assume that there exist other devices still running these other ancient versions of Windows 10.

Add support for dark title bars on Windows 10 1809-2004 

---

TwitchDownloaderCore/Tools/FfmpegMetadata.cs
TwitchDownloaderCore/TwitchHelper.cs
TwitchDownloaderCore/TwitchObjects/Gql/GqlVideoResponse.cs
TwitchDownloaderCore/VideoDownloader.cs

Include VOD description in video metadata if present

---

TwitchDownloaderWPF/PageChatDownload.xaml.cs
TwitchDownloaderWPF/PageChatRender.xaml.cs
TwitchDownloaderWPF/PageChatUpdate.xaml.cs
TwitchDownloaderWPF/PageClipDownload.xaml.cs
TwitchDownloaderWPF/PageQueue.xaml
TwitchDownloaderWPF/PageQueue.xaml.cs
TwitchDownloaderWPF/PageVodDownload.xaml.cs
TwitchDownloaderWPF/Services/ThumbnailService.cs
TwitchDownloaderWPF/WindowMassDownload.xaml
TwitchDownloaderWPF/WindowMassDownload.xaml.cs
TwitchDownloaderWPF/WindowQueueOptions.xaml.cs
TwitchDownloaderWPF/WindowRangeSelect.xaml.cs
TwitchDownloaderWPF/WindowSettings.xaml
TwitchDownloaderWPF/WindowSettings.xaml.cs
TwitchDownloaderWPF/WindowUrlList.xaml.cs

- Use URIs when fetching thumbnails so they can be properly cached
- Add design time `DataContext`s to `ItemsControl`s so the intellisense warnings go away
- Add ppOverheat loading animation to WindowMassDownload (and decrease video count from 100 to 50 to match clips)
- Fix incorrect border color on bandwidth throttle checkbox that made it impossible to see

Quality of life GUI improvements

---

TwitchDownloaderCLI/Tools/FfmpegHandler.cs
TwitchDownloaderWPF/MainWindow.xaml.cs
TwitchDownloaderWPF/Translations/Strings.Designer.cs
TwitchDownloaderWPF/Translations/Strings.es.resx
TwitchDownloaderWPF/Translations/Strings.fr.resx
TwitchDownloaderWPF/Translations/Strings.pl.resx
TwitchDownloaderWPF/Translations/Strings.resx
TwitchDownloaderWPF/Translations/Strings.ru.resx
TwitchDownloaderWPF/Translations/Strings.tr.resx
TwitchDownloaderWPF/Translations/Strings.zh.resx

Add FFmpeg download progress to WPF & move FFmpeg progress writing to a separate thread in CLI so the download isn't stalled by writing to the console

Better FFmpeg download progress reporting

---

TwitchDownloaderCore/ChatRenderer.cs
TwitchDownloaderCore/Tools/HighlightIcons.cs

- Properly render new bit badge messages
| Twitch website | ![image](https://github.com/lay295/TwitchDownloader/assets/72096833/e8f7b75f-ecf1-4afc-a86b-5012b6f7a333) |
|--------|--------|
| Chat render before | ![image](https://github.com/lay295/TwitchDownloader/assets/72096833/bcba306b-136b-4c42-b865-73a9ad44dda3) |
| Chat render after | ![image](https://github.com/lay295/TwitchDownloader/assets/72096833/063e863f-09be-4e55-8cbb-12386298f4b7) | 
- Also some minor performance & maintainability improvements

Support highlighting new bit badge notifications

---

TwitchDownloaderCore/Chat/ChatJson.cs

- This fixes a huge issue with the chat updater that somehow went unnoticed
- This also enables deserializing UTF16 BOM and UTF32 BOM files
-  Fixes #764

Deserialize chat json files without relying on the file extension

---

TwitchDownloaderCore/Chat/ChatJson.cs
TwitchDownloaderCore/Extensions/ReadOnlySpanExtensions.cs
TwitchDownloaderCore/Extensions/StringExtensions.cs
TwitchDownloaderCore/Tools/FilenameService.cs
TwitchDownloaderCore/Tools/TimeSpanHFormat.cs
TwitchDownloaderCore/Tools/UrlTimeCode.cs
TwitchDownloaderWPF/PageChatDownload.xaml.cs
TwitchDownloaderWPF/PageChatUpdate.xaml.cs
TwitchDownloaderWPF/PageVodDownload.xaml.cs
TwitchDownloaderWPF/WindowQueueOptions.xaml.cs

No promises that CLI filename templates will be ready soon, just some much needed cleanup and quote mark escape support

Prerequisites for CLI filename template support

---

TwitchDownloaderTests/GlobalUsings.cs
TwitchDownloaderTests/ReadOnlySpanTryReplaceNonEscapedTests.cs
TwitchDownloaderTests/StringReplaceAnyTests.cs
TwitchDownloaderTests/TimeSpanHFormatTests.cs
TwitchDownloaderTests/TwitchDownloaderTests.csproj
TwitchDownloaderTests/UrlTimeCodeTests.cs
TwitchDownloaderWPF.sln

Developing complex algorithms like `TimeSpanHFormat` without unit tests has been a huge pain. I'm finally making tests so if I have to touch anything in the future I don't break the edge cases.
Making tests for new/existing tools is and will continue to be optional. If you don't want the tests to show up as member references in your intellisense, right click the test project in the solution explorer and select _unload project_.

Add unit tests

---

TwitchDownloaderCore/ChatRenderer.cs
TwitchDownloaderCore/Tools/HighlightIcons.cs

Works for watch streak messages with and without custom messages
| | Before | After |
|--------|--------|--------|
| Website | ![image](https://github.com/lay295/TwitchDownloader/assets/72096833/a14002a6-5e19-4921-a09f-d52cf943f8fb) | N/A |
| Render | ![image](https://github.com/lay295/TwitchDownloader/assets/72096833/72ca5fbd-5c47-49aa-8032-fc849ad68b12) | ![image](https://github.com/lay295/TwitchDownloader/assets/72096833/bed73d69-1c0a-4bc3-8afe-ffa1956e3022) |
Names redacted for privacy

Add support for correctly rendering watch streak messages

---

TwitchDownloaderCLI/Modes/Arguments/VideoDownloadArgs.cs
TwitchDownloaderCLI/Modes/DownloadVideo.cs
TwitchDownloaderCLI/README.md
TwitchDownloaderCore/TwitchHelper.cs
TwitchDownloaderCore/VideoDownloader.cs
TwitchDownloaderWPF/PageVodDownload.xaml.cs

The implementation is a bit rough, but it can be improved by the new M3U8 class in #834.
- Resolves #862

Support downloading VODs as audio only

---

TwitchDownloaderCore/Tools/FilenameService.cs
TwitchDownloaderTests/FilenameServiceTests.cs

- Fix custom parameters not working if more than one is used
- Update `{date}` because the old one sucked. If anyone wants the old behavior back, it can be achieved with `{date_custom="Mdyy"}`
- Add some basic unit tests

Fix issues with filename templates

---

TwitchDownloaderWPF/App.xaml.cs
TwitchDownloaderWPF/PageChatDownload.xaml.cs
TwitchDownloaderWPF/PageChatRender.xaml.cs
TwitchDownloaderWPF/PageChatUpdate.xaml.cs
TwitchDownloaderWPF/PageClipDownload.xaml.cs
TwitchDownloaderWPF/PageQueue.xaml.cs
TwitchDownloaderWPF/PageVodDownload.xaml.cs
TwitchDownloaderWPF/WindowMassDownload.xaml.cs
TwitchDownloaderWPF/WindowUrlList.xaml.cs

This change feels so good to use.
Setting the window owner also fixes another issue where the main window could be brought to the foreground on top of another application but the currently open dialog remained behind said other application.

Make all windows start in the center of the screen or their parent window

---

TwitchDownloaderCore/ClipDownloader.cs

- Fixes #906 
- Fixes #905 
- Fixes #895

Fix lockup when downloading clips with metadata

---

TwitchDownloaderWPF/App.config
TwitchDownloaderWPF/Properties/Settings.Designer.cs
TwitchDownloaderWPF/Properties/Settings.settings
TwitchDownloaderWPF/Translations/Strings.Designer.cs
TwitchDownloaderWPF/Translations/Strings.es.resx
TwitchDownloaderWPF/Translations/Strings.fr.resx
TwitchDownloaderWPF/Translations/Strings.pl.resx
TwitchDownloaderWPF/Translations/Strings.resx
TwitchDownloaderWPF/Translations/Strings.ru.resx
TwitchDownloaderWPF/Translations/Strings.tr.resx
TwitchDownloaderWPF/Translations/Strings.uk.resx
TwitchDownloaderWPF/Translations/Strings.zh.resx
TwitchDownloaderWPF/WindowSettings.xaml
TwitchDownloaderWPF/WindowSettings.xaml.cs

The dialog also no longer saves settings on closing.

Add Save/Cancel/Reset buttons to settings window

---

.github/workflows/build-pr.yml
.github/workflows/build.yml
README.md
TwitchDownloaderCLI/Properties/PublishProfiles/MacOSArm64.pubxml

The binary seems to work as expected according to feedback from several users

Add Macos arm64 binary

---

.github/workflows/build-pr.yml
.github/workflows/build.yml

It's not like we're distributing obfuscated closed source code, may as well include the debug symbols for easier diagnosing of field reports.

Emit debug symbols alongside CI builds and embedded within release builds

---

TwitchDownloaderCore/ClipDownloader.cs

Actually fixes #914 this time, I promise

Fix clip downloader sometimes getting stuck when encoding metadata

---

TwitchDownloaderWPF/PageChatRender.xaml
TwitchDownloaderWPF/PageQueue.xaml
TwitchDownloaderWPF/PageQueue.xaml.cs
TwitchDownloaderWPF/Translations/Strings.Designer.cs
TwitchDownloaderWPF/Translations/Strings.es.resx
TwitchDownloaderWPF/Translations/Strings.fr.resx
TwitchDownloaderWPF/Translations/Strings.pl.resx
TwitchDownloaderWPF/Translations/Strings.resx
TwitchDownloaderWPF/Translations/Strings.ru.resx
TwitchDownloaderWPF/Translations/Strings.tr.resx
TwitchDownloaderWPF/Translations/Strings.uk.resx
TwitchDownloaderWPF/Translations/Strings.zh.resx
TwitchDownloaderWPF/TwitchTasks/ChatDownloadTask.cs
TwitchDownloaderWPF/TwitchTasks/ChatRenderTask.cs
TwitchDownloaderWPF/TwitchTasks/ChatUpdateTask.cs
TwitchDownloaderWPF/TwitchTasks/ClipDownloadTask.cs
TwitchDownloaderWPF/TwitchTasks/ITwitchTask.cs
TwitchDownloaderWPF/TwitchTasks/VodDownloadTask.cs

- Addresses more improvements from #560 
- Changed the chat render page FFmpeg arg icon from a triangle to a circle

Add right-click menu to task queue

---

TwitchDownloaderCore.Tests/M3U8Tests.cs
TwitchDownloaderCore/Tools/M3U8.cs

- Culture-invariant int/uint/decimal parsing + tests
- Fixes #933 
- Non-throwing value parsing for non-critical metadata

Fix M3U8 failing to parse when the application is using certain languages

---

TwitchDownloaderCore.Tests/M3U8ExtensionTests.cs
TwitchDownloaderCore/Extensions/M3U8Extensions.cs
TwitchDownloaderCore/VideoDownloader.cs

Fixes #935, see that for a more detailed discussion.
This also fixes a separate bug with stream quality selection when downloading VODs. Twitch's Usher endpoint to list stream qualities sometimes returns a `1080p60` stream quality with full framerate info, but sometimes that stream is returned as `Source` with no framerate info. Because there was no exact match for the stream name between the quality dropdown and the response when downloading, the logic would fall through to this: https://github.com/lay295/TwitchDownloader/blob/e48a04b2dd07c089cec63380c9814af17a4f36f4/TwitchDownloaderCore/Extensions/M3U8Extensions.cs#L77
However, in this case the framerate is 0 for the `Source` stream, which breaks this calculation. The other streams in the response do have framerate info when this …

Fix VOD download trimming and quality selection

---

TwitchDownloaderCore/Extensions/M3U8Extensions.cs
TwitchDownloaderCore/Tools/M3U8StreamQualityComparer.cs

- Resolves #952 
Accommodates for various edge cases involving the source quality. Still not perfect, but more resiliency is always better.

Improve handling of some source quality related edge cases

---

README_it.md
TwitchDownloaderWPF/Translations/Strings.it.resx

Added an Italian readme and added Italian files for the application language.

Italian language implementation

---

TwitchDownloaderWPF/Translations/Strings.Designer.cs
TwitchDownloaderWPF/Translations/Strings.es.resx
TwitchDownloaderWPF/Translations/Strings.fr.resx
TwitchDownloaderWPF/Translations/Strings.it.resx
TwitchDownloaderWPF/Translations/Strings.pl.resx
TwitchDownloaderWPF/Translations/Strings.resx
TwitchDownloaderWPF/Translations/Strings.ru.resx
TwitchDownloaderWPF/Translations/Strings.tr.resx
TwitchDownloaderWPF/Translations/Strings.uk.resx
TwitchDownloaderWPF/Translations/Strings.zh.resx
TwitchDownloaderWPF/WindowQueueOptions.xaml
TwitchDownloaderWPF/WindowQueueOptions.xaml.cs

- Adds a combobox with a handful of predefined quality options to choose from
- If the chosen quality is not found for a given VOD/Clip then it will default to source (like the CLI)
- The quality picker is only available for the VOD/Clip/URL mass downloaders because the pages already have a quality picker that is accurate to the specific video
- Resolves #581

Add preferred quality selector to the mass downloaders

---

TwitchDownloaderCore/Chat/ChatJson.cs

Recover even more missing information from legacy chats if possible

Better legacy chat support

---

TwitchDownloaderCore.Tests/ToolTests/M3U8Tests.cs
TwitchDownloaderCore/Tools/M3U8.cs

Fix M3U8.ToString() being culture dependent

---

TwitchDownloaderCore.Tests/ExtensionTests/M3U8ExtensionTests.cs
TwitchDownloaderCore/Extensions/M3U8Extensions.cs

Support `best` and `worst` keywords in CLI video downloader

---

TwitchDownloaderCore/ChatDownloader.cs

Fix chat download fail due to null `CommentVideo.creator`

---

TwitchDownloaderCore/ChatDownloader.cs
TwitchDownloaderCore/ChatRenderer.cs
TwitchDownloaderCore/ChatUpdater.cs
TwitchDownloaderCore/TwitchHelper.cs

~~Due to an abundance of 403s from 7TV,~~ instead of outright failing, we will instead log a message that a given provider returned HTTP 400-500 and continue execution.
- Fixes #1013

Catch exceptions when fetching images from third party emote providers

---

TwitchDownloaderCore/ChatRenderer.cs
TwitchDownloaderCore/TwitchHelper.cs

- Fixes #1017
- Perform less repeat dictionary lookups

Do not blindly assume non-system emojis always decode successfully

---

TwitchDownloaderWPF/App.xaml
TwitchDownloaderWPF/PageChatDownload.xaml
TwitchDownloaderWPF/PageChatDownload.xaml.cs
TwitchDownloaderWPF/PageChatRender.xaml
TwitchDownloaderWPF/PageChatUpdate.xaml
TwitchDownloaderWPF/PageChatUpdate.xaml.cs
TwitchDownloaderWPF/PageClipDownload.xaml
TwitchDownloaderWPF/PageClipDownload.xaml.cs
TwitchDownloaderWPF/PageQueue.xaml
TwitchDownloaderWPF/PageVodDownload.xaml
TwitchDownloaderWPF/PageVodDownload.xaml.cs
TwitchDownloaderWPF/Themes/Dark.xaml
TwitchDownloaderWPF/Themes/Light.xaml
TwitchDownloaderWPF/WindowQueueOptions.xaml
TwitchDownloaderWPF/WindowSettings.xaml

Fix WPF styling

---

TwitchDownloaderWPF/App.config
TwitchDownloaderWPF/PageChatDownload.xaml
TwitchDownloaderWPF/PageVodDownload.xaml
TwitchDownloaderWPF/Properties/Settings.Designer.cs
TwitchDownloaderWPF/Properties/Settings.settings

Double maximum WPF VOD download threads

---

TwitchDownloaderCLI/Modes/Arguments/TwitchDownloaderArgs.cs
TwitchDownloaderCore/Interfaces/ITaskLogger.cs
TwitchDownloaderCore/Tools/DownloadTools.cs
TwitchDownloaderCore/Tools/VideoDownloadThread.cs
TwitchDownloaderCore/VideoDownloader.cs

Mostly refactoring of download threads

Add some verbose logs to video download threads

---

TwitchDownloaderCore/ClipDownloader.cs
TwitchDownloaderCore/Tools/FfmpegMetadata.cs
TwitchDownloaderWPF/PageChatDownload.xaml.cs
TwitchDownloaderWPF/PageChatUpdate.xaml.cs
TwitchDownloaderWPF/PageClipDownload.xaml.cs
TwitchDownloaderWPF/PageVodDownload.xaml.cs
TwitchDownloaderWPF/Translations/Strings.Designer.cs
TwitchDownloaderWPF/Translations/Strings.es.resx
TwitchDownloaderWPF/Translations/Strings.fr.resx
TwitchDownloaderWPF/Translations/Strings.it.resx
TwitchDownloaderWPF/Translations/Strings.ja.resx
TwitchDownloaderWPF/Translations/Strings.pl.resx
TwitchDownloaderWPF/Translations/Strings.pt-br.resx
TwitchDownloaderWPF/Translations/Strings.resx
TwitchDownloaderWPF/Translations/Strings.ru.resx
TwitchDownloaderWPF/Translations/Strings.tr.resx
TwitchDownloaderWPF/Translations/Strings.uk.resx
TwitchDownloaderWPF/Translations/Strings.zh.resx
TwitchDownloaderWPF/WindowMassDownload.xaml.cs
TwitchDownloaderWPF/WindowUrlList.xaml.cs

Apparently Twitch doesn't purge clips from deleted channels.

Fix NRE when downloading clips from deleted channels

---

TwitchDownloaderCLI/Modes/Arguments/ChatDownloadArgs.cs
TwitchDownloaderCLI/Modes/Arguments/VideoDownloadArgs.cs
TwitchDownloaderCLI/Modes/DownloadChat.cs
TwitchDownloaderCLI/README.md
TwitchDownloaderCLI/Tools/PreParseArgs.cs
TwitchDownloaderCore/ChatDownloader.cs
TwitchDownloaderCore/ChatUpdater.cs
TwitchDownloaderCore/Options/ChatDownloadOptions.cs
TwitchDownloaderWPF/PageChatDownload.xaml
TwitchDownloaderWPF/PageChatDownload.xaml.cs
TwitchDownloaderWPF/PageVodDownload.xaml
TwitchDownloaderWPF/README.md
TwitchDownloaderWPF/Translations/Strings.Designer.cs
TwitchDownloaderWPF/Translations/Strings.es.resx
TwitchDownloaderWPF/Translations/Strings.fr.resx
TwitchDownloaderWPF/Translations/Strings.it.resx
TwitchDownloaderWPF/Translations/Strings.pl.resx
TwitchDownloaderWPF/Translations/Strings.pt-br.resx
TwitchDownloaderWPF/Translations/Strings.resx
TwitchDownloaderWPF/Translations/Strings.ru.resx
TwitchDownloaderWPF/Translations/Strings.tr.resx
TwitchDownloaderWPF/Translations/Strings.uk.resx
TwitchDownloaderWPF/Translations/Strings.zh-cn.resx

I got some feedback from some users that "Download Threads" (from the Vod page) is more clear than "Connections" on the chat download page.

Rename chat connections to download threads

---

TwitchDownloaderCLI/Modes/DownloadVideo.cs
TwitchDownloaderCore/ChatDownloader.cs
TwitchDownloaderCore/ChatUpdater.cs
TwitchDownloaderCore/Options/VideoDownloadOptions.cs
TwitchDownloaderCore/TwitchHelper.cs
TwitchDownloaderWPF/PageChatDownload.xaml.cs
TwitchDownloaderWPF/PageChatUpdate.xaml.cs
TwitchDownloaderWPF/PageVodDownload.xaml.cs
TwitchDownloaderWPF/WindowQueueOptions.xaml.cs
TwitchDownloaderWPF/WindowUrlList.xaml.cs

Twitch video IDs broke the int32 barrier yesterday.

Use int64 for video IDs (fixes #1057)

---

TwitchDownloaderCore/Chat/ChatHtml.cs
TwitchDownloaderCore/Chat/ChatJson.cs
TwitchDownloaderCore/Tools/FfmpegMetadata.cs
TwitchDownloaderWPF/WindowSettings.xaml.cs

- Use minimally required file permissions
- Fix FFMetadata link
- Cleanup WPF culture combobox initialization

Minor cleanup

---

TwitchDownloaderWPF/MainWindow.xaml.cs
TwitchDownloaderWPF/PageChatDownload.xaml.cs
TwitchDownloaderWPF/PageChatRender.xaml.cs
TwitchDownloaderWPF/PageChatUpdate.xaml.cs
TwitchDownloaderWPF/PageClipDownload.xaml.cs
TwitchDownloaderWPF/PageQueue.xaml.cs
TwitchDownloaderWPF/PageVodDownload.xaml.cs
TwitchDownloaderWPF/WindowQueueOptions.xaml.cs
TwitchDownloaderWPF/WindowSettings.xaml.cs
TwitchDownloaderWPF/WindowUrlList.xaml.cs

Hopefully this fixes message boxes being able to appear in the background and blocking user input.

Fix WPF message boxes rarely appearing in the background

---

TwitchDownloaderWPF/App.xaml
TwitchDownloaderWPF/App.xaml.cs
TwitchDownloaderWPF/MainWindow.xaml
TwitchDownloaderWPF/MainWindow.xaml.cs
TwitchDownloaderWPF/Services/ThemeService.cs
TwitchDownloaderWPF/WindowMassDownload.xaml
TwitchDownloaderWPF/WindowMassDownload.xaml.cs
TwitchDownloaderWPF/WindowOldVideoCacheManager.xaml
TwitchDownloaderWPF/WindowOldVideoCacheManager.xaml.cs
TwitchDownloaderWPF/WindowQueueOptions.xaml
TwitchDownloaderWPF/WindowQueueOptions.xaml.cs
TwitchDownloaderWPF/WindowRangeSelect.xaml
TwitchDownloaderWPF/WindowRangeSelect.xaml.cs
TwitchDownloaderWPF/WindowSettings.xaml
TwitchDownloaderWPF/WindowSettings.xaml.cs
TwitchDownloaderWPF/WindowUrlList.xaml
TwitchDownloaderWPF/WindowUrlList.xaml.cs

By setting the dark titlebar during `SourceInitialized`, we don't need to force a repaint by spawning a virtually invisible window.
Forcing a repaint is still necessary to change the titlebar theme after first present though, such as reacting to system theme changes.

Improve WPF dark titlebar handling

---

TwitchDownloaderCLI/Modes/Arguments/ChatRenderArgs.cs
TwitchDownloaderCLI/Modes/RenderChat.cs
TwitchDownloaderCLI/README.md
TwitchDownloaderCore/ChatRenderer.cs
TwitchDownloaderCore/Extensions/SKColorExtensions.cs
TwitchDownloaderCore/Options/ChatRenderOptions.cs
TwitchDownloaderCore/Resources/chat-template.html
TwitchDownloaderWPF/App.config
TwitchDownloaderWPF/PageChatRender.xaml
TwitchDownloaderWPF/PageChatRender.xaml.cs
TwitchDownloaderWPF/Properties/Settings.Designer.cs
TwitchDownloaderWPF/Properties/Settings.settings
TwitchDownloaderWPF/Translations/Strings.Designer.cs
TwitchDownloaderWPF/Translations/Strings.es.resx
TwitchDownloaderWPF/Translations/Strings.fr.resx
TwitchDownloaderWPF/Translations/Strings.it.resx
TwitchDownloaderWPF/Translations/Strings.ja.resx
TwitchDownloaderWPF/Translations/Strings.pl.resx
TwitchDownloaderWPF/Translations/Strings.pt-br.resx
TwitchDownloaderWPF/Translations/Strings.resx
TwitchDownloaderWPF/Translations/Strings.ru.resx
TwitchDownloaderWPF/Translations/Strings.tr.resx
TwitchDownloaderWPF/Translations/Strings.uk.resx
TwitchDownloaderWPF/Translations/Strings.zh-cn.resx

- Fixes #1047 
<details><summary>Image comparison</summary>
<p>
| Before | After |
|--------|--------|
| ![image](https://github.com/lay295/TwitchDownloader/assets/72096833/da28775c-ef31-43a1-bf1e-5516d2e1eaf6) | ![image](https://github.com/lay295/TwitchDownloader/assets/72096833/f087cd6d-4f19-4ae6-a861-485573f62a03) |
| ![image](https://github.com/lay295/TwitchDownloader/assets/72096833/c393d923-1033-4561-aee5-4c783dab0bd3) | ![image](https://github.com/lay295/TwitchDownloader/assets/72096833/511c2252-1477-44b5-bd0e-fd0874e58bb1) |
| ![image](https://github.com/lay295/TwitchDownloader/assets/72096833/68482d54-08c3-4742-b2a0-ea7f0e48c353) | ![image](https://github.com/lay295/TwitchDownloader/assets/72096833/72fb48d6-b156-4986-bd66-1aa89d58d2f9) |
Works with alternating background colors …

Improve readable colors algorithm and make it optional

---

TwitchDownloaderCore.Tests/ToolTests/FilenameServiceTests.cs
TwitchDownloaderCore/Tools/FilenameService.cs

Fix WPF crash when getting filename for streams with missing info

---

.github/workflows/build-pr.yml
.github/workflows/build.yml

Update github actions

---

TwitchDownloaderCore/ChatDownloader.cs
TwitchDownloaderCore/ChatRenderer.cs
TwitchDownloaderCore/ChatUpdater.cs
TwitchDownloaderCore/ClipDownloader.cs
TwitchDownloaderCore/TsMerger.cs
TwitchDownloaderCore/VideoDownloader.cs

Delete output file on error if it's empty

---

TwitchDownloaderCore/ChatDownloader.cs
TwitchDownloaderCore/ChatRenderer.cs
TwitchDownloaderCore/ChatUpdater.cs
TwitchDownloaderCore/ClipDownloader.cs
TwitchDownloaderCore/Tools/FfmpegConcatList.cs
TwitchDownloaderCore/Tools/FfmpegMetadata.cs
TwitchDownloaderCore/Tools/M3U8.cs
TwitchDownloaderCore/TsMerger.cs
TwitchDownloaderCore/VideoDownloader.cs

This technically addresses #750, but most video players don't seem to like the EIA-608 subtitles so a manual method will be needed.

New video finalization method

---

TwitchDownloaderCLI/Modes/Arguments/VideoDownloadArgs.cs
TwitchDownloaderCLI/Modes/DownloadVideo.cs
TwitchDownloaderCLI/README.md
TwitchDownloaderCore/Options/VideoDownloadOptions.cs
TwitchDownloaderCore/Tools/Enums.cs
TwitchDownloaderCore/VideoDownloader.cs
TwitchDownloaderWPF/App.config
TwitchDownloaderWPF/PageVodDownload.xaml
TwitchDownloaderWPF/PageVodDownload.xaml.cs
TwitchDownloaderWPF/Properties/Settings.Designer.cs
TwitchDownloaderWPF/Properties/Settings.settings
TwitchDownloaderWPF/README.md
TwitchDownloaderWPF/Translations/Strings.Designer.cs
TwitchDownloaderWPF/Translations/Strings.es.resx
TwitchDownloaderWPF/Translations/Strings.fr.resx
TwitchDownloaderWPF/Translations/Strings.it.resx
TwitchDownloaderWPF/Translations/Strings.ja.resx
TwitchDownloaderWPF/Translations/Strings.pl.resx
TwitchDownloaderWPF/Translations/Strings.pt-br.resx
TwitchDownloaderWPF/Translations/Strings.resx
TwitchDownloaderWPF/Translations/Strings.ru.resx
TwitchDownloaderWPF/Translations/Strings.tr.resx
TwitchDownloaderWPF/Translations/Strings.uk.resx
TwitchDownloaderWPF/Translations/Strings.zh-cn.resx

I tried 3 different solutions to the problem but only this one provided good results and also didn't corrupt the rest of the video.
- Fixes #531 
- Fixes #863 
- Fixes #556

Add `Safe` video trim mode to circumvent rare encoding issues

---

.github/workflows/build-pr.yml
TwitchDownloaderCore.Tests/ToolTests/FilenameServiceTests.cs

Tests are not mandatory for the build steps to run, its just nice to know when tests are failing if you forget to run them locally.

Add test runner job to build-pr workflow

---

TwitchDownloaderCore/VideoDownloader.cs

Disable audio copy after first video finalization failure

---

TwitchDownloaderCLI/Modes/DownloadChat.cs
TwitchDownloaderCLI/Modes/DownloadClip.cs
TwitchDownloaderCLI/Modes/DownloadVideo.cs
TwitchDownloaderCLI/Modes/MergeTs.cs
TwitchDownloaderCLI/Modes/RenderChat.cs
TwitchDownloaderCLI/Modes/UpdateChat.cs
TwitchDownloaderCLI/Tools/FileCollisionHandler.cs

Use Environment.Exit instead of returning null

---

TwitchDownloaderCLI.Tests/ModelTests/TimeDurationTests.cs
TwitchDownloaderCLI/Models/TimeDuration.cs

`36:01:02` will now be properly interpreted as 36 hours, 1 minute, and 2 seconds instead of 36 days, 1 hour, and 2 minutes

Fix parsing CLI time durations >24 hours in timespan notation

---

TwitchDownloaderCore/Tools/FfmpegConcatList.cs

Fix missing audio issues with muted VODs

---

TwitchDownloaderCLI/Modes/Arguments/ChatRenderArgs.cs
TwitchDownloaderCLI/Modes/RenderChat.cs

And just when I thought 1.54.8 would be a perfect release...

Fix being unable to lower `readable-colors` flag in CLI

---

TwitchDownloaderCore/ChatDownloader.cs
TwitchDownloaderCore/ChatRenderer.cs
TwitchDownloaderCore/ChatUpdater.cs
TwitchDownloaderCore/ClipDownloader.cs
TwitchDownloaderCore/VideoDownloader.cs

Fix issues with relative cache paths

---

TwitchDownloaderCLI/Modes/Arguments/ChatDownloadArgs.cs
TwitchDownloaderCLI/Modes/DownloadChat.cs
TwitchDownloaderCore/Options/ChatDownloadOptions.cs

Remove --silent arg from chat downloader

---

TwitchDownloaderCLI/Modes/DownloadVideo.cs
TwitchDownloaderCore/Tools/FilenameService.cs
TwitchDownloaderWPF/PageVodDownload.xaml.cs
TwitchDownloaderWPF/WindowQueueOptions.xaml.cs

FilenameService probably isn't the right place for it, but its not that big of a deal.
- Resolves #994

Add `Audio Only` option to mass downloader preferred quality

---

TwitchDownloaderCore/Tools/FfmpegMetadata.cs

this documentation is correct:
https://ffmpeg.org/ffmpeg-utils.html#Quoting-and-escaping
this is outdated:
https://ffmpeg.org/ffmpeg-formats.html#metadata
Escaping only backslash `\\` is enough but single quotes can be escaped no problem.

Only escape backslashes, single quotes, and newlines when writing ffmetadata

---

TwitchDownloaderCore/TwitchObjects/ChatRoot.cs
TwitchDownloaderWPF/PageChatDownload.xaml.cs
TwitchDownloaderWPF/WindowQueueOptions.xaml.cs

Fix chat trim and timestamp format not being applied when enqueuing from chat page

---

TwitchDownloaderWPF/PageQueue.xaml
TwitchDownloaderWPF/PageQueue.xaml.cs
TwitchDownloaderWPF/TwitchTasks/ChatDownloadTask.cs
TwitchDownloaderWPF/TwitchTasks/ChatRenderTask.cs
TwitchDownloaderWPF/TwitchTasks/ChatUpdateTask.cs
TwitchDownloaderWPF/TwitchTasks/ClipDownloadTask.cs
TwitchDownloaderWPF/TwitchTasks/ITwitchTask.cs
TwitchDownloaderWPF/TwitchTasks/VodDownloadTask.cs
TwitchDownloaderWPF/Utils/WpfTaskProgress.cs
TwitchDownloaderWPF/WindowQueueOptions.xaml.cs

Show detailed statuses in task queue

---

TwitchDownloaderCore/Tools/VideoDownloadThread.cs
TwitchDownloaderCore/VideoDownloader.cs

Old commits that were never merged

Fix not all failed video parts being redownloaded

---

TwitchDownloaderWPF/Extensions/VersionExtensions.cs
TwitchDownloaderWPF/MainWindow.xaml.cs
TwitchDownloaderWPF/Properties/AssemblyInfo.cs

Move WPF version to AssemblyInfo

---

TwitchDownloaderCore/ClipDownloader.cs
TwitchDownloaderCore/Tools/FfmpegMetadata.cs
TwitchDownloaderCore/VideoDownloader.cs

Adds game to `genre` field and `Clipped by: <name>` to clip descriptions. Ascii usernames are also now included in fields containing user names if the display name is non-ascii.

Embed more metadata in videos and clips

---

TwitchDownloaderWPF/Extensions/TextBoxExtensions.cs
TwitchDownloaderWPF/PageChatRender.xaml
TwitchDownloaderWPF/PageChatRender.xaml.cs
TwitchDownloaderWPF/Translations/Strings.Designer.cs
TwitchDownloaderWPF/Translations/Strings.es.resx
TwitchDownloaderWPF/Translations/Strings.fr.resx
TwitchDownloaderWPF/Translations/Strings.it.resx
TwitchDownloaderWPF/Translations/Strings.ja.resx
TwitchDownloaderWPF/Translations/Strings.pl.resx
TwitchDownloaderWPF/Translations/Strings.pt-br.resx
TwitchDownloaderWPF/Translations/Strings.resx
TwitchDownloaderWPF/Translations/Strings.ru.resx
TwitchDownloaderWPF/Translations/Strings.tr.resx
TwitchDownloaderWPF/Translations/Strings.uk.resx
TwitchDownloaderWPF/Translations/Strings.zh-cn.resx
TwitchDownloaderWPF/WindowSettings.xaml
TwitchDownloaderWPF/WindowSettings.xaml.cs

- Addresses a request from #1190

Allow clicking filename/FFmpeg parameters to insert into templates

---

TwitchDownloaderWPF/App.config
TwitchDownloaderWPF/Models/CollisionBehavior.cs
TwitchDownloaderWPF/Properties/Settings.Designer.cs
TwitchDownloaderWPF/Properties/Settings.settings
TwitchDownloaderWPF/Services/FileCollisionService.cs
TwitchDownloaderWPF/Translations/Strings.Designer.cs
TwitchDownloaderWPF/Translations/Strings.es.resx
TwitchDownloaderWPF/Translations/Strings.fr.resx
TwitchDownloaderWPF/Translations/Strings.it.resx
TwitchDownloaderWPF/Translations/Strings.ja.resx
TwitchDownloaderWPF/Translations/Strings.pl.resx
TwitchDownloaderWPF/Translations/Strings.pt-br.resx
TwitchDownloaderWPF/Translations/Strings.resx
TwitchDownloaderWPF/Translations/Strings.ru.resx
TwitchDownloaderWPF/Translations/Strings.tr.resx
TwitchDownloaderWPF/Translations/Strings.uk.resx
TwitchDownloaderWPF/Translations/Strings.zh-cn.resx
TwitchDownloaderWPF/WindowSettings.xaml
TwitchDownloaderWPF/WindowSettings.xaml.cs

Allow customizing file collision handling in the the settings

---

TwitchDownloaderWPF/PageQueue.xaml
TwitchDownloaderWPF/PageQueue.xaml.cs

Add buttons for reordering tasks

---

TwitchDownloaderCLI/Modes/FfmpegHandler.cs
TwitchDownloaderWPF/MainWindow.xaml.cs

The library literally does nothing but provide FFmpeg builds, how is it so hard to maintain that builds are over 4 years out of date??

Fix FFmpeg downloaders fetching >4 year old FFmpeg builds on Windows

---

TwitchDownloaderCore.Tests/ToolTests/HighlightIconsTests.cs
TwitchDownloaderCore/ChatRenderer.cs
TwitchDownloaderCore/Tools/HighlightIcons.cs

Used to render like bottom, now renders as top (parity with Twitch chat).

Render continuing anonymous gift subs correctly

---

TwitchDownloaderCLI/Modes/InfoHandler.cs
TwitchDownloaderCore.Tests/ExtensionTests/M3U8ExtensionTests.cs
TwitchDownloaderCore.Tests/ToolTests/M3U8Tests.cs
TwitchDownloaderCore/Tools/M3U8.cs
TwitchDownloaderCore/Tools/M3U8Parse.cs

This makes parsing stream codecs easier

Better m3u8 codec parsing

---

TwitchDownloaderWPF/WindowMassDownload.xaml.cs

Fix fatal error in mass downloaders when Twitch API lies about having a next page

---

TwitchDownloaderWPF/MainWindow.xaml.cs
TwitchDownloaderWPF/Services/NativeFunctions.cs

I'm surprised this worked previously when not passing as a pointer

Correctly use ref parameter when flashing taskbar icon

---

TwitchDownloaderCore.Tests/ToolTests/HighlightIconsTests.cs
TwitchDownloaderCore/ChatRenderer.cs
TwitchDownloaderCore/Tools/HighlightIcons.cs

Support properly rendering Subtember gift subs

---

TwitchDownloaderCore/TwitchHelper.cs

See #1254 for details. I'm not sure whether this is the proper solution, but in case it is here's a PR for it.

Add null check for emoticon id in TwitchHelper.GetEmotes() (#1254)

---

TwitchDownloaderCore.Tests/ToolTests/M3U8Tests.cs
TwitchDownloaderCore/Tools/DownloadTools.cs
TwitchDownloaderCore/Tools/FfmpegConcatList.cs
TwitchDownloaderCore/Tools/M3U8.cs
TwitchDownloaderCore/Tools/M3U8Parse.cs
TwitchDownloaderCore/Tools/VideoDownloadThread.cs
TwitchDownloaderCore/VideoDownloader.cs

Initial support for AV1/H.265 VODs

---

TwitchDownloaderCore/ChatDownloader.cs

Fix being able to download chats before they start/after they end via the CLI

---

TwitchDownloaderCLI/Modes/CacheHandler.cs
TwitchDownloaderCore/ChatDownloader.cs
TwitchDownloaderCore/ChatRenderer.cs
TwitchDownloaderCore/ChatUpdater.cs
TwitchDownloaderCore/ClipDownloader.cs
TwitchDownloaderCore/Services/CacheDirectoryService.cs
TwitchDownloaderCore/VideoDownloader.cs
TwitchDownloaderWPF/WindowSettings.xaml.cs

- Fixes a bug discovered in #1271

Rewrite cache directory handling

---

TwitchDownloaderCLI/TwitchDownloaderCLI.csproj
TwitchDownloaderWPF/TwitchDownloaderWPF.csproj

System.Text.Json 9.0.X is incompatible with .NET 6

Downgrade Xabe.FFmpeg.Downloader to 5.2.6

---

TwitchDownloaderCLI/Modes/Arguments/UpdateArgs.cs
TwitchDownloaderCLI/Modes/UpdateHandler.cs
TwitchDownloaderCLI/Program.cs
TwitchDownloaderCore/Extensions/VersionExtensions.cs
TwitchDownloaderWPF/MainWindow.xaml.cs

Implements the enhancement described in this issue: #1288 
Creates facilities to enable the auto-update of the CLI without having to manually download the package release every time. 
When a user wants to update the CLI, they can simply run either:
- `TwitchDownloaderCLI.exe update` - First checks if a new version is available, and if it is, prompts whether it should be installed. If the user selects yes, an update archive is downloaded and extracted and the old executable is renamed to "TwitchDownloaderCLI.exe.bak"
- `TwitchDownloaderCLI.exe update -f` or `TwitchDownloaderCLI.exe update --force` - Same as above but bypasses the prompt asking whether to proceed with the update or not
Like the GUI auto-update, this code relies on the following URL to get information about a new version: …

Add auto-update functionality to CLI

---

TwitchDownloaderWPF/App.config
TwitchDownloaderWPF/PageChatDownload.xaml.cs
TwitchDownloaderWPF/PageChatRender.xaml.cs
TwitchDownloaderWPF/PageChatUpdate.xaml.cs
TwitchDownloaderWPF/PageClipDownload.xaml.cs
TwitchDownloaderWPF/PageVodDownload.xaml.cs
TwitchDownloaderWPF/Properties/Settings.Designer.cs
TwitchDownloaderWPF/Properties/Settings.settings
TwitchDownloaderWPF/Translations/Strings.Designer.cs
TwitchDownloaderWPF/Translations/Strings.es.resx
TwitchDownloaderWPF/Translations/Strings.fr.resx
TwitchDownloaderWPF/Translations/Strings.it.resx
TwitchDownloaderWPF/Translations/Strings.ja.resx
TwitchDownloaderWPF/Translations/Strings.pl.resx
TwitchDownloaderWPF/Translations/Strings.pt-br.resx
TwitchDownloaderWPF/Translations/Strings.resx
TwitchDownloaderWPF/Translations/Strings.ru.resx
TwitchDownloaderWPF/Translations/Strings.tr.resx
TwitchDownloaderWPF/Translations/Strings.uk.resx
TwitchDownloaderWPF/Translations/Strings.zh-cn.resx
TwitchDownloaderWPF/Translations/Strings.zh-tw.resx
TwitchDownloaderWPF/TwitchTasks/TwitchTask.cs
TwitchDownloaderWPF/WindowMassDownload.xaml.cs
TwitchDownloaderWPF/WindowSettings.xaml
TwitchDownloaderWPF/WindowSettings.xaml.cs

Implements the enhancement described in issue https://github.com/lay295/TwitchDownloader/issues/1346
Adds a checkbox in the settings window that hides pp/peepo status animations in the following places:
- VOD Download page
- Clip Download page
- Chat Download page
- Chat Updater page
- Chat Render page
- Task queue page (for each individual task in the queue)
- Search VODs mass downloader window (when a channel's VODs are loading)
- Search Clips mass downloader window (when a channel's clips are loading)

Accessibility enhancement: Add setting to hide pp/peepo status animations

---

TwitchDownloaderCore/Tools/M3U8.cs

- Fixes #1387 
- Fixes not being able to print table info of videos with streams without codecs

Fix crashes when Twitch does not return stream codecs

---

TwitchDownloaderCore/Resources/chat-template.html

Fixes https://github.com/lay295/TwitchDownloader/issues/1397
Sets the character encoding for the template file used for HTML chat downloads to UTF-8. Without setting this in the template file certain characters were appearing incorrectly in the latest Brave browser.

Fix incorrect character encoding for HTML chat download on Brave browser

---

TwitchDownloaderWPF/Properties/Settings.Designer.cs
TwitchDownloaderWPF/Properties/Settings.settings
TwitchDownloaderWPF/Translations/Strings.Designer.cs
TwitchDownloaderWPF/Translations/Strings.es.resx
TwitchDownloaderWPF/Translations/Strings.fr.resx
TwitchDownloaderWPF/Translations/Strings.it.resx
TwitchDownloaderWPF/Translations/Strings.ja.resx
TwitchDownloaderWPF/Translations/Strings.pl.resx
TwitchDownloaderWPF/Translations/Strings.pt-br.resx
TwitchDownloaderWPF/Translations/Strings.resx
TwitchDownloaderWPF/Translations/Strings.ru.resx
TwitchDownloaderWPF/Translations/Strings.tr.resx
TwitchDownloaderWPF/Translations/Strings.uk.resx
TwitchDownloaderWPF/Translations/Strings.zh-cn.resx
TwitchDownloaderWPF/Translations/Strings.zh-tw.resx
TwitchDownloaderWPF/WindowMassDownload.xaml
TwitchDownloaderWPF/WindowMassDownload.xaml.cs

Fixes https://github.com/lay295/TwitchDownloader/issues/1361
Adds a "Recent Channels" combo box to the left of the channel text box in the mass downloader window:
This combo box will remember up to **ten** previous (valid) channel names that have been set in the window. On selecting a channel name in the box, that channel name will be mirrored in the adjacent channel text box to allow it to be set again easily.
Some important notes:
- Channel names are only added to the combo box if they are not already in the list of items 
- Entering an 11th channel name will cause the 1st channel name in the box to be replaced.
These recent channels are also saved in the program settings, which ensures that they will be remembered even if the program is closed and restarted.

QOL Enhancement: Remember recent channels in mass downloader window

---

TwitchDownloaderCore/ChatRenderer.cs
TwitchDownloaderCore/TwitchHelper.cs
TwitchDownloaderCore/TwitchObjects/ChatBadge.cs
TwitchDownloaderCore/TwitchObjects/CheerEmote.cs
TwitchDownloaderCore/TwitchObjects/TwitchEmote.cs

This allows emotes that don't conform to 56x56-64x64 @ 24pt font to still be integer scaled
Fixes #1472

Allow integer scaling small emotes
