lay295/TwitchDownloader

TwitchDownloaderWPF/PageClipDownload.xaml.cs, TwitchDownloaderWPF/PageVodDownload.xaml.cs
Added default filename to saveFileDialog streamer - video title to save some time.
=> Added default filename to saveFileDialog

LICENSE.txt
Should address issue #88 and #99.
=> Add source code MIT license

README.md
I've made an AUR (Arch User Repository) package for TwitchDownloader for more convenient installation on Arch Linux. This adds a link to it in the README.
As a side note, it would also be nice to add a license to this repository.
=> Add AUR info

README.md
- separate GUI and CLI headings
- shorter descriptions
- split long text
- readability
=> Cleanup and formatting of README

README.md, TwitchDownloaderCLI/Options.cs, TwitchDownloaderCLI/Program.cs, TwitchDownloaderCLI/README.md, TwitchDownloaderCore/ChatRenderer.cs, TwitchDownloaderCore/Options/ChatRenderOptions.cs, TwitchDownloaderCore/TwitchHelper.cs, TwitchDownloaderWPF/App.config, TwitchDownloaderWPF/PageChatRender.xaml, TwitchDownloaderWPF/PageChatRender.xaml.cs, TwitchDownloaderWPF/Properties/Settings.settings
=> Add 7tv emotes support

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yaml, .github/ISSUE_TEMPLATE/other.yaml
Pretty simple but should hopefully make the issues a bit more organized
=> Add some basic issue templates

TwitchDownloaderCore/TwitchHelper.cs
=> Fix emojis for non-windows systems

TwitchDownloaderCore/VideoDownloader.cs
it's a small change, fixes https://github.com/lay295/TwitchDownloader/issues/294
=> remove ffmpeg unnecessary output

TwitchDownloaderWPF/MainWindow.xaml.cs
To make troubleshooting issues and app updates easier, add the version number to the GUI title
=> Add version number to GUI window title

TwitchDownloaderCLI/Options.cs
The two args got mixed at some point
=> Fixed --sub-messages and --chat-badges mixup

TwitchDownloaderCLI/Options.cs, TwitchDownloaderCLI/README.md
Updated README; `--embed-emotes` is no longer valid, new syntax is `--embed-emotes=true`
=> Clarify README

README.md
Hey! I created a simple GUI for linux, basically a wrapper for the CLI
it has the basic functionalities, similar design.
https://github.com/mohad12211/twitch-downloader-gui
=> Add note about linux GUI

TwitchDownloaderCore/ChatRenderer.cs
Related issue: #402
Also simplified an if statement with pattern matching
=> Fix rendering issues with messages containing nonfont chars (#402)

TwitchDownloaderCore/TwitchHelper.cs
=> Fix removed twitch emotes throwing 404 (#396)

TwitchDownloaderWPF/ThemeHelper.cs, TwitchDownloaderWPF/WindowQueueOptions.xaml, TwitchDownloaderWPF/WindowQueueOptions.xaml.cs
=> Fix potential theme related crashes

TwitchDownloaderCore/TwitchObjects/ChatRoot.cs
=> Move video poperty above comment property in chatroot

.github/workflows/build-pr.yml, .github/workflows/build.yml
This will build artifacts on push / PR to the main branch, which is really helpful to test changes when you don't have a build system setup (e.g., ability to build linux).
=> CI Builds on PR

TwitchDownloaderCLI/Tools/PathExtensions.cs
Broke this on accident with the CLI rewrite
=> Fix PATH exception on Linux

TwitchDownloaderCore/ChatDownloader.cs, TwitchDownloaderCore/ChatRenderer.cs, TwitchDownloaderCore/ChatUpdater.cs, TwitchDownloaderCore/ClipDownloader.cs, TwitchDownloaderCore/TwitchHelper.cs, TwitchDownloaderCore/TwitchObjects/ChatRoot.cs, TwitchDownloaderCore/VideoDownloader.cs, TwitchDownloaderWPF/App.config, TwitchDownloaderWPF/PageChatDownload.xaml.cs, TwitchDownloaderWPF/PageChatRender.xaml, TwitchDownloaderWPF/PageChatRender.xaml.cs, TwitchDownloaderWPF/PageChatUpdate.xaml.cs, TwitchDownloaderWPF/PageQueue.xaml, TwitchDownloaderWPF/PageQueue.xaml.cs, TwitchDownloaderWPF/PageVodDownload.xaml.cs, TwitchDownloaderWPF/Properties/Settings.Designer.cs, TwitchDownloaderWPF/Properties/Settings.settings, TwitchDownloaderWPF/TwitchTasks/ChatDownloadTask.cs, TwitchDownloaderWPF/TwitchTasks/ChatRenderTask.cs, TwitchDownloaderWPF/TwitchTasks/ChatUpdateTask .cs, TwitchDownloaderWPF/TwitchTasks/ClipDownloadTask.cs, TwitchDownloaderWPF/TwitchTasks/ITwitchTask.cs, TwitchDownloaderWPF/TwitchTasks/VodDownloadTask.cs, TwitchDownloaderWPF/WindowQueueOptions.xaml.cs
- Add cancel button to task queue
- Add finalizers to some classes to cleanup after task finishing or canceling
- Add offline checkbox to chatrender gui page
- Fix emojis with more than 1 codepoint removing more than 1 char from the render fragment string (and sometimes crashing)
- Fixes #461
=> Add cancel button to task queue

TwitchDownloaderCore/ChatRenderer.cs
=> Fix messages first drawing only on whole seconds

TwitchDownloaderCore/ClipDownloader.cs, TwitchDownloaderCore/VideoDownloader.cs
=> Add id verification to videodownload and clipdownload

TwitchDownloaderCore/ChatDownloader.cs, TwitchDownloaderCore/ChatUpdater.cs, TwitchDownloaderCore/Tools/ChatJson.cs, TwitchDownloaderCore/Tools/FfmpegMetadata.cs, TwitchDownloaderCore/TwitchHelper.cs, TwitchDownloaderCore/TwitchObjects/Api/FFZEmote.cs, TwitchDownloaderCore/TwitchObjects/ChatBadge.cs, TwitchDownloaderCore/TwitchObjects/ChatRoot.cs, TwitchDownloaderCore/TwitchObjects/ChatRootInfo.cs, TwitchDownloaderCore/TwitchObjects/Gql/GqlVideoChapterResponse.cs, TwitchDownloaderCore/VideoDownloader.cs
- Add stream chapters to chat downloads
- Add stream chapters to video downloads
- Add stream name to video downloads
- Add stream id to video downloads
- Add streamer name to video downloads
- Add air date to video downloads
- Rework and bump ChatRootVersion to 1.2.1
<br>
- Closes #491
- Closes #323
=> Embed VOD Metadata

TwitchDownloaderWPF/PageChatDownload.xaml, TwitchDownloaderWPF/PageChatRender.xaml, TwitchDownloaderWPF/PageChatUpdate.xaml, TwitchDownloaderWPF/PageClipDownload.xaml, TwitchDownloaderWPF/PageQueue.xaml, TwitchDownloaderWPF/PageVodDownload.xaml, TwitchDownloaderWPF/PageVodDownload.xaml.cs
Fixes #536
As a side effect that I'm sure nobody will complain about, peepo is MASSIVE now
=> Remove vertical padding on StatusBarItems

TwitchDownloaderWPF/PageChatDownload.xaml, TwitchDownloaderWPF/PageChatDownload.xaml.cs, TwitchDownloaderWPF/PageChatRender.xaml, TwitchDownloaderWPF/PageChatRender.xaml.cs, TwitchDownloaderWPF/PageChatUpdate.xaml, TwitchDownloaderWPF/PageChatUpdate.xaml.cs, TwitchDownloaderWPF/PageClipDownload.xaml, TwitchDownloaderWPF/PageClipDownload.xaml.cs, TwitchDownloaderWPF/PageVodDownload.xaml, TwitchDownloaderWPF/PageVodDownload.xaml.cs
=> Add cancel button to regular task pages

TwitchDownloaderCLI/Modes/Arguments/ChatRenderArgs.cs, TwitchDownloaderCLI/Modes/RenderChat.cs, TwitchDownloaderCLI/README.md, TwitchDownloaderWPF/App.config, TwitchDownloaderWPF/PageChatRender.xaml, TwitchDownloaderWPF/PageChatRender.xaml.cs, TwitchDownloaderWPF/Properties/Settings.Designer.cs, TwitchDownloaderWPF/Properties/Settings.settings
- Add option for render sharpening to WPF and CLI
- Closes #482
=> Add sharpening option to chat render

TwitchDownloaderCore/ChatDownloader.cs, TwitchDownloaderCore/ChatRenderer.cs, TwitchDownloaderCore/TwitchObjects/ChatRoot.cs
Expect up to 20% smaller chat JSONs
=> Remove most unused remnants of v5 from ChatRoot.

TwitchDownloaderCore/ChatDownloader.cs, TwitchDownloaderCore/ChatRenderer.cs, TwitchDownloaderCore/ChatUpdater.cs, TwitchDownloaderCore/TwitchHelper.cs
=> Use comment list to only cache required 3rd party emotes, bits, and badges

TwitchDownloaderCLI/Modes/DownloadChat.cs, TwitchDownloaderCLI/Modes/DownloadClip.cs, TwitchDownloaderWPF/PageChatDownload.xaml.cs, TwitchDownloaderWPF/PageClipDownload.xaml.cs, TwitchDownloaderWPF/PageVodDownload.xaml.cs, TwitchDownloaderWPF/WindowUrlList.xaml.cs
- Fix incorrect regex for parsing clip IDs in CLI
- Fix all URL/ID parsing in GUI
- Fixes #573
=> Fix clip id parsing

TwitchDownloaderCore/Tools/FfmpegMetadata.cs, TwitchDownloaderCore/VideoDownloader.cs
- Fix crash when the chapter game is null - fixes #583 
- Wrap ffmetadata path in quotes
=> Fix vod metadata related errors

TwitchDownloaderWPF/App.config, TwitchDownloaderWPF/PageChatDownload.xaml.cs, TwitchDownloaderWPF/PageChatRender.xaml.cs, TwitchDownloaderWPF/PageChatUpdate.xaml.cs, TwitchDownloaderWPF/PageClipDownload.xaml.cs, TwitchDownloaderWPF/PageVodDownload.xaml.cs, TwitchDownloaderWPF/Properties/Settings.Designer.cs, TwitchDownloaderWPF/Properties/Settings.settings, TwitchDownloaderWPF/Translations/Strings.Designer.cs, TwitchDownloaderWPF/Translations/Strings.fr.resx, TwitchDownloaderWPF/Translations/Strings.pl.resx, TwitchDownloaderWPF/Translations/Strings.resx, TwitchDownloaderWPF/Translations/Strings.tr.resx, TwitchDownloaderWPF/WindowMassDownload.xaml.cs, TwitchDownloaderWPF/WindowQueueOptions.xaml.cs, TwitchDownloaderWPF/WindowSettings.xaml, TwitchDownloaderWPF/WindowSettings.xaml.cs, TwitchDownloaderWPF/WindowUrlList.xaml.cs
- Fix crash when using an improper URL/ID in chatdownload page
- Fix inconsistent use of UTC and local time
- Add option to choose between UTC and local time - fixes #585 
- Fix render button getting permanently disabled after the first render. How I missed this, I have no clue
=> Gui improvements

TwitchDownloaderCore/VideoDownloader.cs
=> Fix the videodownload ffmpeg logger causing an uncatchable exception on slow drives

TwitchDownloaderCore/ChatDownloader.cs
- Fix null `commentResponse.data.video.comments` causing downloads to fail - Fixes #605 
- Use `HttpContentJsonExtensions` instead of `Newtonsoft` - theoretically reduces allocations
=> Fix null commentResponse.data.video.comments causing downloads to fail

TwitchDownloaderCore/ChatRenderer.cs, TwitchDownloaderCore/TwitchHelper.cs
=> Escape user-defined regex inputs

TwitchDownloaderCore/TwitchObjects/ChatRoot.cs
=> Fix NRE when cloning message with null emotes list

TwitchDownloaderCore/TwitchHelper.cs
=> Ensure success status code on channel 3rd party emotes

TwitchDownloaderCore/ChatRenderer.cs, TwitchDownloaderCore/Tools/HighlightMessage.cs
- Add another sub message: _X is paying forward the Gift they got from Y_
- Support channel point highlighted messages. Will be very useful if we ever do live chat downloading.
- Fix potential false positive highlight
=> Support channel point highlighted messages

TwitchDownloaderWPF/Services/AvailableCultures.cs, TwitchDownloaderWPF/Translations/Strings.ru.resx, TwitchDownloaderWPF/TwitchDownloaderWPF.csproj
=> Add initial Russian translation

TwitchDownloaderWPF/MainWindow.xaml.cs
For issue #316 added support for templates subfolders. Templates now can be configured like this and all the data will be stored in actual subfolders.
=> Issue #316 added subfolders template support

TwitchDownloaderWPF/App.xaml.cs, TwitchDownloaderWPF/MainWindow.xaml.cs, TwitchDownloaderWPF/PageChatRender.xaml.cs, TwitchDownloaderWPF/Services/CultureService.cs, TwitchDownloaderWPF/Services/ThemeService.cs, TwitchDownloaderWPF/Services/WindowsThemeService.cs
- Addresses the base issue that lead to #653
- General cleanup
=> Better culture changing, cleanup

TwitchDownloaderCore/VideoDownloader.cs
=> Fix OverflowException during video finalization

TwitchDownloaderWPF/WindowQueueOptions.xaml.cs
=> Fix enqueue dialogue assuming chat renders are always mp4

.github/workflows/build-pr.yml, .github/workflows/build.yml, README.md, TwitchDownloaderCLI/Properties/PublishProfiles/LinuxArm64.pubxml
* Add publish profile for arm64
* Add CI for arm64
* Update readme
Thanks
=> TwitchDownloaderCLI : Support building for arm64

TwitchDownloaderCLI/TwitchDownloaderCLI.csproj, TwitchDownloaderCore/TwitchDownloaderCore.csproj, TwitchDownloaderWPF/MainWindow.xaml.cs, TwitchDownloaderWPF/Translations/Strings.Designer.cs, TwitchDownloaderWPF/Translations/Strings.fr.resx, TwitchDownloaderWPF/Translations/Strings.resx, TwitchDownloaderWPF/TwitchDownloaderWPF.csproj
Not merging yet incase anything is broken and I missed it. Any tests on weird/old Windows installs are appreciated.
=> Upgrade nuget packages

TwitchDownloaderCore/ChatRenderer.cs
I finally fixed it. Makes rendering a tiny bit slower, oh well.
| Before | After |
|--------|--------|
| ![image](https://github.com/lay295/TwitchDownloader/assets/72096833/e1fdb623-c4bf-4c53-b1ae-82bb7df0a1e1) | ![image](https://github.com/lay295/TwitchDownloader/assets/72096833/39a0e929-1d5a-40c7-bb6b-1e53152da765) |
=> Fix incorrectly rendered text outlines for RTL characters

TwitchDownloaderCLI/Modes/Arguments/ChatRenderArgs.cs, TwitchDownloaderCLI/README.md, TwitchDownloaderCore/ChatRenderer.cs, TwitchDownloaderWPF/App.config, TwitchDownloaderWPF/PageChatRender.xaml, TwitchDownloaderWPF/Properties/Settings.Designer.cs, TwitchDownloaderWPF/Properties/Settings.settings, TwitchDownloaderWPF/README.md, TwitchDownloaderWPF/Translations/Strings.Designer.cs, TwitchDownloaderWPF/Translations/Strings.fr.resx, TwitchDownloaderWPF/Translations/Strings.resx
So much simpler now and chats look much more natural!
=> Better dispersion

TwitchDownloaderWPF/Services/WindowsThemeService.cs
Dear users; please update from windows 7, it's a huge security risk.
- Fixes #777
=> Fix ManagementException on old windows versions

TwitchDownloaderCLI/Program.cs
=> Use CommandLine types instead of FileVersionInfo

TwitchDownloaderCLI/Program.cs
=> Remove working directory override in CLI

TwitchDownloaderCore/Tools/ThrottledStream.cs, TwitchDownloaderCore/VideoDownloader.cs
This solves the problem for real this time, I promise.
The implementation isn't super clean though, a code review from others is welcomed. I have an alternative implementation I prefer more but it's causing weird async behavior, so it remains stashed for now.
- Fixes #798
- Fixes #772 
- Fixes #749
- Fixes #665
- Fixes #563
- Fixes #265
=> Videodownload 99% stop fix

TwitchDownloaderCLI/Modes/UpdateChat.cs, TwitchDownloaderCore/ChatUpdater.cs, TwitchDownloaderCore/TwitchObjects/StvEmoteFlags.cs, TwitchDownloaderWPF/README.md, TwitchDownloaderWPF/WindowMassDownload.xaml.cs, TwitchDownloaderWPF/WindowQueueOptions.xaml.cs
Fixes a few typos and such in the comments
=> Spelling fixes

TwitchDownloaderCore/Chat/ChatJson.cs, TwitchDownloaderCore/ChatDownloader.cs, TwitchDownloaderCore/Tools/TwitchRegex.cs
=> Fix incorrect message.bits_spent for chats between v5 shutdown and 1.51.2

TwitchDownloaderWPF/Models/ThemeResourceDictionaryModel.cs, TwitchDownloaderWPF/Services/DefaultThemeService.cs, TwitchDownloaderWPF/Services/ThemeService.cs, TwitchDownloaderWPF/WindowSettings.xaml.cs
=> Fix some theme related crashes

TwitchDownloaderCore/Chat/ChatJson.cs, TwitchDownloaderCore/TwitchObjects/ChatRoot.cs
=> Fix old chats with stringified streamer ids being undeserializable

README.md, README_tr.md, TwitchDownloaderWPF/Translations/Strings.tr.resx
I finally learned how to do it in one go. 👯
=> minor translation additions

TwitchDownloaderWPF/Translations/Strings.uk.resx
minor updates to the spelling in Ukrainian localization
translation of new lines
=> Update Strings.uk.resx (Ukrainian localization)

TwitchDownloaderCore/ClipDownloader.cs
Hopefully this properly solves #914
=> Fix bad clip metadata file path

.github/workflows/build-pr.yml, .github/workflows/build.yml
If github ever goes through with the deprecations then this should help keep us from being affected
=> Update github actions

TwitchDownloaderCLI/Modes/DownloadVideo.cs, TwitchDownloaderCore/Options/VideoDownloadOptions.cs, TwitchDownloaderCore/TwitchHelper.cs, TwitchDownloaderCore/VideoDownloader.cs, TwitchDownloaderWPF/PageVodDownload.xaml.cs, TwitchDownloaderWPF/Translations/Strings.Designer.cs, TwitchDownloaderWPF/Translations/Strings.es.resx, TwitchDownloaderWPF/Translations/Strings.fr.resx, TwitchDownloaderWPF/Translations/Strings.it.resx, TwitchDownloaderWPF/Translations/Strings.pl.resx, TwitchDownloaderWPF/Translations/Strings.resx, TwitchDownloaderWPF/Translations/Strings.ru.resx, TwitchDownloaderWPF/Translations/Strings.tr.resx, TwitchDownloaderWPF/Translations/Strings.uk.resx, TwitchDownloaderWPF/Translations/Strings.zh.resx, TwitchDownloaderWPF/WindowOldVideoCacheManager.xaml, TwitchDownloaderWPF/WindowOldVideoCacheManager.xaml.cs
I was testing something and accidentally had my several-gigabyte test cache deleted because it was very old :/
Anyways so I decided to make this user prompt.
Screenshots from the Windows GUI (fake test data):
(yes I fixed the select all button text)
=> Prompt user for old cache deletion

TwitchDownloaderCore/ChatRenderer.cs
=> Fix badges and bits not obeying custom scaling when the font size is set to 24

README_ptbr.md, TwitchDownloaderWPF/Translations/Strings.ptbr.resx
Add both a translated README file along with fully translated strings for the GUI application.
=> Add Brazilian Portuguese Language

TwitchDownloaderCore/VideoDownloader.cs
=> Fix chapters not properly reacting to video cropping

TwitchDownloaderCLI/Modes/DownloadVideo.cs, TwitchDownloaderCore/Options/VideoDownloadOptions.cs, TwitchDownloaderCore/Tools/FfmpegMetadata.cs, TwitchDownloaderCore/VideoDownloader.cs, TwitchDownloaderWPF/PageVodDownload.xaml.cs, TwitchDownloaderWPF/WindowQueueOptions.xaml.cs
- Actually fixes #716 
- Fixes #1003
=> Fix incorrect video finalization percentages and chapters caused by bad math

TwitchDownloaderWPF/WindowUrlList.xaml.cs
=> Several URL list fixes

TwitchDownloaderCore/ChatRenderer.cs, TwitchDownloaderCore/Tools/HighlightIcons.cs
It doesn't look like much, but on transparent renders the difference is night and day.
| Before | ![image](https://github.com/lay295/TwitchDownloader/assets/72096833/acef4068-21d4-4b8a-a6e6-632997876ef4) |
|--------|--------|
| After  | ![image](https://github.com/lay295/TwitchDownloader/assets/72096833/e1475ca3-6c24-499a-9d13-d61218429d31) |
=> Outline sub/highlight icons

TwitchDownloaderWPF/Translations/Strings.Designer.cs, TwitchDownloaderWPF/Translations/Strings.es.resx, TwitchDownloaderWPF/Translations/Strings.fr.resx, TwitchDownloaderWPF/Translations/Strings.it.resx, TwitchDownloaderWPF/Translations/Strings.pl.resx, TwitchDownloaderWPF/Translations/Strings.pt-br.resx, TwitchDownloaderWPF/Translations/Strings.resx, TwitchDownloaderWPF/Translations/Strings.ru.resx, TwitchDownloaderWPF/Translations/Strings.tr.resx, TwitchDownloaderWPF/Translations/Strings.uk.resx, TwitchDownloaderWPF/Translations/Strings.zh.resx, TwitchDownloaderWPF/WindowOldVideoCacheManager.xaml, TwitchDownloaderWPF/WindowOldVideoCacheManager.xaml.cs
=> Add context menu to cache deletion window

README.md, README_es.md, README_it.md, README_ja.md, README_pt-br.md, README_tr.md, README_zh-cn.md, TwitchDownloaderWPF/Translations/Strings.zh-cn.resx, TwitchDownloaderWPF/TwitchDownloaderWPF.csproj
Updated the Simplified Chinese translations and reformatted all the README files to be more Markdown compliant.
=> Update Simplified Chinese and Adjust All READMEs

TwitchDownloaderWPF/Translations/Strings.zh-cn.resx
Sorry for missing some translations.
=> Add Missing Simplified Chinese Translations

TwitchDownloaderWPF/Translations/Strings.zh-cn.resx
Fix some mistakes, add original text for words with similar meanings
=> Fix Some Simplified Chinese Translations

TwitchDownloaderCore/Tools/FfmpegConcatList.cs, TwitchDownloaderCore/VideoDownloader.cs
=> Remove query string when writing concat list

TwitchDownloaderCLI/README.md
=> Link to enum flags explanation in CLI readme

README.md, README_ru.md, TwitchDownloaderWPF/Translations/Strings.ru.resx
Russian readme has been added and the existing Russian localization has been updated with bug fixes.
=> Russian readme and updated russian localization

TwitchDownloaderCore/Options/ChatRenderOptions.cs
=> Fix zero division caused by a non-zero low update rate and a low framerate

TwitchDownloaderWPF/Translations/Strings.zh-cn.resx
Just changed some text and added two missing colons :/
=> Update Simplified Chinese Translation

TwitchDownloaderCore/ClipDownloader.cs
=> Improve clip downloader quality detection

TwitchDownloaderWPF/WindowQueueOptions.xaml
=> Add `worst` keyword to enqueuer preferred quality combobox

TwitchDownloaderCore/VideoDownloader.cs
=> Uncap max_streams

TwitchDownloaderWPF/WindowUrlList.xaml.cs
=> Fix crash when enqueuing a clip from a deleted streamer in URL mass downloader

TwitchDownloaderWPF/Translations/Strings.Designer.cs, TwitchDownloaderWPF/Translations/Strings.es.resx, TwitchDownloaderWPF/Translations/Strings.fr.resx, TwitchDownloaderWPF/Translations/Strings.it.resx, TwitchDownloaderWPF/Translations/Strings.ja.resx, TwitchDownloaderWPF/Translations/Strings.pl.resx, TwitchDownloaderWPF/Translations/Strings.pt-br.resx, TwitchDownloaderWPF/Translations/Strings.resx, TwitchDownloaderWPF/Translations/Strings.ru.resx, TwitchDownloaderWPF/Translations/Strings.tr.resx, TwitchDownloaderWPF/Translations/Strings.uk.resx, TwitchDownloaderWPF/Translations/Strings.zh-cn.resx, TwitchDownloaderWPF/WindowQueueOptions.xaml.cs
=> Create missing queue folder instead of erroring

TwitchDownloaderCore/ChatDownloader.cs
=> Fix backfilling commenter info progress going over 100%

README.md, README_zh-cn.md, README_zh-tw.md, TwitchDownloaderWPF/Services/AvailableCultures.cs, TwitchDownloaderWPF/Translations/Strings.zh-tw.resx, TwitchDownloaderWPF/TwitchDownloaderWPF.csproj
- Provided preliminary Traditional Chinese translation
- Fixed some formatting issues
=> Update Chinese Translations

TwitchDownloaderCore.Tests/IdParseTests.cs, TwitchDownloaderCore/Tools/IdParse.cs
The old scheme no longer works either, all old video and clips URLs no longer work
=> Update kick-support branch to support new Kick URL scheme

TwitchDownloaderWPF/WindowQueueOptions.xaml.cs
I absolutely hate this
- Fixes #1261
=> Fix missing file extension when enqueuing JSON chats with Gzip compression

TwitchDownloaderCLI.Tests/TwitchDownloaderCLI.Tests.csproj, TwitchDownloaderCore.Tests/TwitchDownloaderCore.Tests.csproj
Forgot to stage these in #1276
=> Bump test nuget packages

TwitchDownloaderCore/Chat/ChatHtml.cs, TwitchDownloaderCore/Chat/ChatJson.cs, TwitchDownloaderCore/Chat/ChatText.cs, TwitchDownloaderCore/ChatDownloader.cs, TwitchDownloaderCore/ChatUpdater.cs, TwitchDownloaderCore/Options/ChatDownloadOptions.cs, TwitchDownloaderCore/Options/ChatUpdateOptions.cs, TwitchDownloaderWPF/PageChatDownload.xaml.cs, TwitchDownloaderWPF/PageChatUpdate.xaml.cs, TwitchDownloaderWPF/WindowQueueOptions.xaml.cs
=> Allow CLI to compress JSON, HTML, and TXT chat files

TwitchDownloaderCLI.Tests/TwitchDownloaderCLI.Tests.csproj, TwitchDownloaderCLI/TwitchDownloaderCLI.csproj, TwitchDownloaderCore.Tests/TwitchDownloaderCore.Tests.csproj, TwitchDownloaderCore/Resources/THIRD-PARTY-LICENSES.txt, TwitchDownloaderWPF/PageChatRender.xaml.cs, TwitchDownloaderWPF/TwitchDownloaderWPF.csproj
=> Bump nuget packages

TwitchDownloaderCore/Extensions/M3U8Extensions.cs
=> Fix crash when multiple non-30fps qualities of the same resolution are available

TwitchDownloaderCore/TwitchHelper.cs, TwitchDownloaderWPF/Translations/Strings.Designer.cs, TwitchDownloaderWPF/Translations/Strings.es.resx, TwitchDownloaderWPF/Translations/Strings.fr.resx, TwitchDownloaderWPF/Translations/Strings.it.resx, TwitchDownloaderWPF/Translations/Strings.ja.resx, TwitchDownloaderWPF/Translations/Strings.pl.resx, TwitchDownloaderWPF/Translations/Strings.pt-br.resx, TwitchDownloaderWPF/Translations/Strings.resx, TwitchDownloaderWPF/Translations/Strings.ru.resx, TwitchDownloaderWPF/Translations/Strings.tr.resx, TwitchDownloaderWPF/Translations/Strings.uk.resx, TwitchDownloaderWPF/Translations/Strings.zh-cn.resx, TwitchDownloaderWPF/Translations/Strings.zh-tw.resx, TwitchDownloaderWPF/WindowMassDownload.xaml, TwitchDownloaderWPF/WindowMassDownload.xaml.cs
=> Allow video mass downloader to sort by video type

TwitchDownloaderCore/VideoDownloader.cs
Fixes a bug discovered in #1320 where very old (~2016 and earlier) muted highlights could not be downloaded (or played on the Twitch website)
=> Workaround to fix downloading very old muted highlights

TwitchDownloaderCore/Tools/DownloadTools.cs
=> Restore VOD unmuting

TwitchDownloaderCore/TwitchHelper.cs
=> Better emote provider error handling

.github/workflows/build-pr.yml, .github/workflows/build.yml
Ubuntu 20.04 is being deprecated
=> Bump ubuntu runners to 24.04

TwitchDownloaderCore/ChatDownloader.cs
I don't know if this is the solution we want to go with, just making this PR to build the changes and give it to ZFG
=> let last thread download until the end

TwitchDownloaderCore/ChatDownloader.cs
=> Fix comment offsets when all comments are more than 5 seconds out of sync

TwitchDownloaderCore/Tools/VideoDownloadThread.cs, TwitchDownloaderCore/VideoDownloader.cs
=> Retune video downloader

TwitchDownloaderCore/ChatDownloader.cs, TwitchDownloaderCore/Tools/FfmpegMetadata.cs, TwitchDownloaderCore/TwitchHelper.cs, TwitchDownloaderWPF/PageChatDownload.xaml.cs, TwitchDownloaderWPF/PageChatUpdate.xaml.cs, TwitchDownloaderWPF/PageVodDownload.xaml.cs
=> Workaround for Twitch API not returning video length for new videos

TwitchDownloaderWPF/PageVodDownload.xaml.cs
=> Fix being unable to trim videos in WPF when the API doesn't return a length

TwitchDownloaderWPF/PageVodDownload.xaml.cs
Can you tell I wrote the last commit without thinking?
=> Fix being able to specify a trim end before the trim start when a video has a length of 0

TwitchDownloaderCore/ChatDownloader.cs
=> Fix being unable to download chats from VODs with wrong lengths

TwitchDownloaderCLI/Modes/UpdateHandler.cs
=> Apply previous file permissions after updating CLI

TwitchDownloaderCore/TwitchHelper.cs
- Fixes #1373 
- Lowered HttpClient timeout to 20s
=> Better error handling when fetching third party emotes

TwitchDownloaderCore/ChatDownloader.cs, TwitchDownloaderCore/TwitchHelper.cs, TwitchDownloaderCore/TwitchObjects/Api/STVGlobalEmoteResponse.cs, TwitchDownloaderCore/TwitchObjects/ChatRoot.cs, TwitchDownloaderCore/TwitchObjects/TwitchEmote.cs
=> Fix chat downloader not setting `isZeroWidth` for 3rd party emotes

TwitchDownloaderWPF/WindowSettings.xaml
=> Link to culture-agnostic custom DateTime/TimeSpan format pages in settings window

TwitchDownloaderCLI/Modes/FfmpegHandler.cs, TwitchDownloaderCLI/Modes/UpdateHandler.cs, TwitchDownloaderCLI/TwitchDownloaderCLI.csproj, TwitchDownloaderCore/TwitchDownloaderCore.csproj, TwitchDownloaderCore/TwitchHelper.cs
=> Switch from Mono.Posix.NETStandard to Mono.Posix

TwitchDownloaderCore/Tools/VideoDownloadThread.cs
Hopefully addresses the root cause of #1402
=> Add temporary workaround for VOD downloading issue

TwitchDownloaderCLI/Modes/InfoHandler.cs, TwitchDownloaderCore/ChatDownloader.cs, TwitchDownloaderCore/ChatUpdater.cs, TwitchDownloaderCore/ClipDownloader.cs, TwitchDownloaderCore/Tools/ClipAssetQualityComparer.cs, TwitchDownloaderCore/Tools/FfmpegMetadata.cs, TwitchDownloaderCore/TwitchHelper.cs, TwitchDownloaderCore/TwitchObjects/Gql/GqlShareClipRenderStatusResponse.cs, TwitchDownloaderWPF/PageClipDownload.xaml.cs
=> Switch to new clip API

TwitchDownloaderCLI/Modes/InfoHandler.cs, TwitchDownloaderCore.Tests/ModelTests/M3U8VideoQualitiesTests.cs, TwitchDownloaderCore/ClipDownloader.cs, TwitchDownloaderCore/Extensions/M3U8Extensions.cs, TwitchDownloaderCore/Models/ClipVideoQualities.cs, TwitchDownloaderCore/Models/ClipVideoQuality.cs, TwitchDownloaderCore/Models/ClipVideoQualityComparer.cs, TwitchDownloaderCore/Models/Interfaces/IVideoQualities.cs, TwitchDownloaderCore/Models/Interfaces/IVideoQuality.cs, TwitchDownloaderCore/Models/M3U8VideoQualities.cs, TwitchDownloaderCore/Models/M3U8VideoQuality.cs, TwitchDownloaderCore/Models/Resolution.cs, TwitchDownloaderCore/Models/VideoQualities.cs, TwitchDownloaderCore/Tools/ClipQualityComparer.cs, TwitchDownloaderCore/TwitchHelper.cs, TwitchDownloaderCore/TwitchObjects/Gql/GqlClipTokenResponse.cs, TwitchDownloaderCore/VideoDownloader.cs, TwitchDownloaderWPF/PageClipDownload.xaml.cs, TwitchDownloaderWPF/PageVodDownload.xaml.cs
=> Better clip/video quality handling + support portrait clips

TwitchDownloaderWPF/Services/ClipboardService.cs
=> Ignore all errors when setting clipboard

TwitchDownloaderWPF/MainWindow.xaml.cs, TwitchDownloaderWPF/PageChatRender.xaml, TwitchDownloaderWPF/PageChatRender.xaml.cs
=> Fix render settings resetting after app updates

TwitchDownloaderCore/Tools/VideoDownloadState.cs, TwitchDownloaderCore/Tools/VideoDownloadThread.cs, TwitchDownloaderCore/VideoDownloader.cs
=> Partially rewrite video downloader

TwitchDownloaderCLI/Models/Enums.cs, TwitchDownloaderCLI/Modes/CacheHandler.cs, TwitchDownloaderCLI/Modes/UpdateHandler.cs, TwitchDownloaderCLI/Tools/FileCollisionHandler.cs, TwitchDownloaderCLI/Tools/UserPrompt.cs
=> Fix several CLI crashes when standard input isn't available

TwitchDownloaderCore/ChatRenderer.cs, TwitchDownloaderCore/TwitchObjects/ChatBadge.cs, TwitchDownloaderCore/TwitchObjects/CheerEmote.cs, TwitchDownloaderCore/TwitchObjects/TwitchEmote.cs
=> Fix scaling of non-2x emotes

TwitchDownloaderWPF/App.xaml.cs, TwitchDownloaderWPF/MainWindow.xaml.cs, TwitchDownloaderWPF/PageChatRender.xaml.cs
- Fixes #1448
- Fixes #1444 
- Fixes #1440
=> Fix issues when loading settings after an update

TwitchDownloaderCLI/Modes/Arguments/ChatRenderArgs.cs, TwitchDownloaderCLI/Modes/RenderChat.cs, TwitchDownloaderCLI/README.md, TwitchDownloaderCore/Chat/ChatJson.cs, TwitchDownloaderCore/ChatRenderer.cs, TwitchDownloaderCore/Options/ChatRenderOptions.cs, TwitchDownloaderCore/TwitchHelper.cs, TwitchDownloaderWPF/App.config, TwitchDownloaderWPF/PageChatRender.xaml, TwitchDownloaderWPF/PageChatRender.xaml.cs, TwitchDownloaderWPF/Properties/Settings.Designer.cs, TwitchDownloaderWPF/Properties/Settings.settings, TwitchDownloaderWPF/README.md, TwitchDownloaderWPF/Translations/Strings.Designer.cs, TwitchDownloaderWPF/Translations/Strings.es.resx, TwitchDownloaderWPF/Translations/Strings.fr.resx, TwitchDownloaderWPF/Translations/Strings.it.resx, TwitchDownloaderWPF/Translations/Strings.ja.resx, TwitchDownloaderWPF/Translations/Strings.pl.resx, TwitchDownloaderWPF/Translations/Strings.pt-br.resx, TwitchDownloaderWPF/Translations/Strings.resx, TwitchDownloaderWPF/Translations/Strings.ru.resx, TwitchDownloaderWPF/Translations/Strings.tr.resx, TwitchDownloaderWPF/Translations/Strings.uk.resx, TwitchDownloaderWPF/Translations/Strings.zh-cn.resx, TwitchDownloaderWPF/Translations/Strings.zh-tw.resx
=> Support rendering user avatars

TwitchDownloaderCLI/Modes/InfoHandler.cs
=> Escape video info when generating info tables

TwitchDownloaderCore/ChatRenderer.cs, TwitchDownloaderCore/Tools/HighlightIcons.cs
It's not perfect, but it's the best we can do with what little info Twitch saves in the VOD chat
=> Properly render combo messages

TwitchDownloaderCore/Models/ClipVideoQualities.cs, TwitchDownloaderCore/Models/ClipVideoQuality.cs, TwitchDownloaderCore/Models/M3U8VideoQualities.cs, TwitchDownloaderCore/Models/VideoQualities.cs, TwitchDownloaderWPF/WindowQueueOptions.xaml.cs
=> Support `portrait` keyword in quality selector

TwitchDownloaderWPF/TwitchTasks/ChatDownloadTask.cs, TwitchDownloaderWPF/TwitchTasks/TwitchTask.cs, TwitchDownloaderWPF/TwitchTasks/VodDownloadTask.cs, TwitchDownloaderWPF/Utils/LiveVideoMonitor.cs
=> Refresh task thumbnail after livestream ends

TwitchDownloaderCore/ChatRenderer.cs, TwitchDownloaderCore/TwitchObjects/ChatBadge.cs, TwitchDownloaderCore/TwitchObjects/CheerEmote.cs, TwitchDownloaderCore/TwitchObjects/TwitchEmote.cs
I give up on SnapResize
- Fixes #1487
=> Finally fix scaling of bits, emotes, and emojis

TwitchDownloaderCore/Tools/HighlightIcons.cs, TwitchDownloaderCore/TwitchHelper.cs
=> Fix crash when cache fails to find image in offline mode
